### PR TITLE
Replace splashes to remove OmniWallet branding

### PR DESCRIPTION
**Pull request by zathras-crypto**
This PR replaces the splash screens for the QT UI.

### CODE REVIEW

**Comment by dexX7** [comment]
Ah.. "This branch is out-of-date with the base branch".

Can you please rebase? :)

**Comment by dexX7** [comment]
This is really a bit annoying, sorry. I'll take some time later and setup a dummy repo to play around with the settings. I hope we can preserve the "no forced pushes" and "must pass CI" properties, but without this rather silly requirement.

**Comment by zathras-crypto** [comment]
Rebased :)

**Comment by dexX7** [comment]
Awesome, thanks! Then I'm going to merge this one, then the (again rebased hehe) release notes, afterwards the version bump and then I'm going to tag `0.0.10-rc1`! :)

**Comment by zathras-crypto** [comment]
Awesome!

**Pull request merged**
