### PR TITLE
Back port fixes & improvements from develop

### PR DESCRIPTION
**Pull request by zathras-crypto**
This PR backports fixes and improvements from the 0.2 development branch to 0.0.11.

The changes backported are as follows:

https://github.com/OmniLayer/omnicore/pull/436 - Improve parsing performance
https://github.com/OmniLayer/omnicore/pull/439 - Fix incorrect value from getTotalTokens when fees are cached
https://github.com/OmniLayer/omnicore/pull/447 - Set minimum fee distribution threshold and protect against empty distributions
https://github.com/OmniLayer/omnicore/pull/448 - Check for fee distribution when total number of tokens is changed

Note #436 has been partially backported, as some of the work is based on changes in Bitcoin 0.13.

Thanks
Z

### CODE REVIEW

**Comment by dexX7** [comment]
Not sure what's up with Travis CI, but I tested it locally with:

```sh
./src/test/test_omnicore
```
```sh
./qa/pull-tester/omnicore-rpc-tests.sh true
```

And both test suits pass. :)

Would you say, this is ready?

**Comment by dexX7** [comment]
Can you please also reference the pull requests you ported back?

**Comment by zathras-crypto** [comment]
I wasn't sure what branch to pull against, I guessed we would work 'omnicore-0.0.10' until ready and then push to master, but I'm open to whatever approach you want to use dude...

Re refs, sure I can do that though to note not "all" of the performance PR was ported back (since some of it relies on 0.13 Bitcoin stuff).

**Comment by dexX7** [comment]
> I wasn't sure what branch to pull against, I guessed we would work 'omnicore-0.0.10' until ready and then push to master, but I'm open to whatever approach you want to use dude...

I'm not really sure either. If we leave `master` as it is and build 0.0.11.3 based on `omnicore-0.0.10`, we can at some point merge the `develop` branch and pick up all the stuff anyway, but this seems a bit messy.

**Comment by zathras-crypto** [comment]
> I'm not really sure either. If we leave master as it is and build 0.0.11.3 based on omnicore-0.0.10, we can at some point merge the develop branch and pick up all the stuff anyway, but this seems a bit messy.

Can you let me know how you'd prefer to do it mate?  I genuinely don't mind how we do it :)

> Can you please also reference the pull requests you ported back?

Added following to description:

The changes backported are as follows:

https://github.com/OmniLayer/omnicore/pull/436 - Improve parsing performance
https://github.com/OmniLayer/omnicore/pull/439 - Fix incorrect value from getTotalTokens when fees are cached
https://github.com/OmniLayer/omnicore/pull/447 - Set minimum fee distribution threshold and protect against empty distributions
https://github.com/OmniLayer/omnicore/pull/448 - Check for fee distribution when total number of tokens is changed

Note #436 has been partially backported, as some of the work is based on changes in Bitcoin 0.13.

**Comment by dexX7** [comment]
> Can you let me know how you'd prefer to do it mate?

For the sake of making a decision, I'd say, let's merge against the `master` branch, and hope that this won't create any incompatibilities, when later trying to merge `develop` into it.  :)

**Comment by zathras-crypto** [comment]
I've changed the base to master...

**Comment by dexX7** [comment]
Hmm, looks like I'm unable to merge:

```
remote: Resolving deltas: 100% (76/76), completed with 16 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
To git@github.com:OmniLayer/omnicore
 ! [remote rejected] master -> master (protected branch hook declined)
```

We need to check with @achamely how the `master` branch is protected (in contrast to `develop`), I guess it's due to the failing Travis CI checks.

**Pull request merged**
