### PR TITLE
Update base to Bitcoin Core 0.10.4

### PR DESCRIPTION
**Pull request by dexX7**
This pull request updates the base to Bitcoin Core 0.10.4.

See the [release notes for Bitcoin Core 0.10.4](https://github.com/OmniLayer/omnicore/blob/c2e7baf2bdb2e2c163bcadaebe68ee00c9a27e7c/doc/release-notes.md).

I resolved the merge conflict via 3fc4be164662106486d67ae4446dbe5c090c5583, and in addition I updated the READMEs and Omni Core release notes via 9406da0e684746732cdea755bf357dd5d72c567e and 2de9bba0f58e45202f686108bd06ba5aca7114ee.

~~I'm going to push a seperate PR to bump the Omni Core version to release candidate 2 soon.~~

I bumped the release status to "rc2" via a293fcefe67d1a9d77d4323d1c96a936a4f45ff7.

### CODE REVIEW

**Comment by dexX7** [comment]
This actually makes me wonder how we deal with Omni Core version numbers. I only bumped the release status:
```
define(_OMNICORE_VERSION_MILESTONE, 0)
define(_OMNICORE_VERSION_MAJOR, 0)
define(_OMNICORE_VERSION_MINOR, 10)
define(_OMNICORE_VERSION_PATCH, 0)
define(_OMNICORE_VERSION_BUILD, 0)
define(_OMNICORE_VERSION_STATUS, rc2)
```

However, I actually believe we should have also bumped the version number, but this doesn't currently work well with this schema. Would it be a build or patch bump? As result, we'd release 0.0.10.1, which also doesn't feel right..

**Comment by zathras-crypto** [comment]
Well technically it would be a patch (or even minor) because we are changing the codebase but agree it doesn't really feel right since 0.0.10.0 is not released yet.  

I think the way you have done it is good, but I'd also be happy with 0.0.10.1 if needed (nothing says we have to *release* every version we make - 0.0.10.1 could simply be our first 0.0.10 public release)

**Comment by zathras-crypto** [comment]
Building to test now

**Comment by zathras-crypto** [comment]
FYI

```
  CXX      omnicore/libbitcoin_server_a-activation.o
In file included from omnicore/activation.cpp:12:0:
./omnicore/version.h:51:37: error: ‘OMNICORE_VERSION_BUILD’ was not declared in this scope
                     +           1 * OMNICORE_VERSION_BUILD;
                                     ^
cc1plus: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
make[2]: *** [omnicore/libbitcoin_server_a-activation.o] Error 1
make[2]: Leaving directory `/home/zathras/github/build/omnicore/src'
```

Investigating now...

**Comment by dexX7** [comment]
I updated the unit tests, and at least the CI tests should pass now.

I'm not able to reproduce the error you described. Does it also happen, if you start from scratch, with `make clean`, `./autogen.sh`, `./configure`, `make`?

**Comment by zathras-crypto** [comment]
Same problem after a ```make clean``` and I'm just running another test after redoing ```autogen.sh``` & ```configure```

**Comment by dexX7** [comment]
That's surprising. Besides the change from `rc1` to `rc2` I don't see how there is any change that may be related.

**Comment by zathras-crypto** [comment]
Quick bit of testing, seems fine, all commands tested returned expected results & all checkpoints passed.  

OK to merge bud, thanks :)

**Comment by dexX7** [comment]
Thanks! :) Will merge, and tag RC2 after the meeting.

**Pull request merged**
