### PR TITLE
Add new RPC to list pending Omni transactions

### LINKED ISSUE #211: Request: Unconfirmed transactions are processed and applied to balances
Due to some excellent work from @dexX7 we now have unconfirmed *transaction* support in the next release (0.0.10) of Omni Core.  

This means (assuming the transaction is in the mempool) we can query a transaction hash before it has confirmed and decode it, and thus provide data about the Omni transaction (excluding validity).

There is a request to support unconfirmed balances in OmniChest's API - in a nutshell if I can:

> http://omnichest.info/requeststat.aspx?stat=balance&prop=1&address=1BitcoinAddress
can return something like
{
  confirmed: 8.7
  unconfirmed: -5
}
can you do that? :)

Now since OmniChest is moving more and more towards just being a scraper for Omni Core to ensure all data is from the reference client, there seems little point in adding that logic to 'Chest.  On the flip side it's not like we can just run an unconfirmed transaction through state processing to add the capability to Core either.

So, couple of Q's really - value & priority of having address lookups show incoming pending balances, and if I'm missing a straight forward approach (because otherwise I'm thinking whilst decoding a unconfirmed transaction is one thing, actually manipulating the state with transactions that aren't on the chain yet seems frought with potential pitfalls and probably needs some very careful consideration)

Thanks
Z

### PR DESCRIPTION
**Pull request by dexX7**
The new RPC `"omni_listpendingtransactions"` can be used to retrieve a list of pending Omni transactions.

This resolves #211.

### CODE REVIEW

**Comment by dexX7** [comment]
I haven't done tests with a very full mempool, and I'm not sure how long the parsing may take. It blocks the mempool only for a short time though, and most of the time is going to be spent in `populateRPCTransactionObject()`.

**Comment by zathras-crypto** [comment]
I've tested this with a mempool with ~1350 transactions, and there is no lag when executing ```omni_listpendingtransactions``` :) 

I'll report back once I've seen a pending transaction in there...

**Comment by dexX7** [comment]
Ah, that's great. So it's very cheap to check, whether the transactions have markers.

I assume a mempool filled with Omni transactions has no unexpected behavior, given that it's pretty similar to standard `"omni_gettransaction"` or `"omni_listtransactions"` calls. Maybe even a bit faster, because the transaction is still unconfirmed, and the inputs available in the UTXO cache.

**Comment by dexX7** [comment]
I tested it locally with a few thousand transactions, and there was no notable delay. I'm not sure, to which degree caching and so on plays a role, but on the other hand, querying the mempool is very fast, so most of the work is spent for populating the JSON results, and this on it's own is nothing new.

Currently the alternative would be to use `getrawmempool` manually, and then `omni_gettransaction` over and over again, which is without a doubt less convenient and slower.

I'm going ahead with the merge given the absence of NACKs (although I'd really prefer clear ACKs).

**Pull request merged**
