### PR TITLE
API Connector placeholder PR

### PR DESCRIPTION
**Pull request by zathras-crypto**
This PR is a work in progress and is not ready for merging.  It's for me to track changes and to gather feedback.

I've been working offline for some time on 'Chest infrastructure testing out some methods for integration.  This is me attempting to clean up some of that work and consolidate some of it here on GitHub.

In essence it's about being able to track changes down to granular state updates, and being able to feed that data to an external listener through HTTP(s) POSTs.

Every time an update is made to the state, that change is turned into a JSON object and given a unique sequence number and stored in a local database.  If the `omniapiurl=` parameter is specified, these JSON objects containing each change are pushed to the specified URL via POST.  The local updates database can be queried, providing a more granular look into changes to the state.  Queries can be by sequence number or by the trigger (either a block or transaction).

It's probably easier to give a few examples to show what I mean:

Looking at updates by their sequence number:

```
$ src/omnicore-cli omni_getupdate 5000 5001
[
    {
        "updatetype" : "balance",
        "updatedelta" : {
            "address" : "1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P",
            "propertyid" : "1",
            "amount" : "0.45149352",
            "balance" : "2081.22450214",
            "reserved" : "0.00000000"
        },
        "updatesequencenumber" : 5000,
        "updatetrigger" : "block",
        "updatetriggerobject" : "0000000000000006e37b95902722f17ec58325f16f6e9643a0e871e1a38fb9d5"
    },
    {
        "updatetype" : "balance",
        "updatedelta" : {
            "address" : "1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P",
            "propertyid" : "1",
            "amount" : "0.15009992",
            "balance" : "2081.37460206",
            "reserved" : "0.00000000"
        },
        "updatesequencenumber" : 5001,
        "updatetrigger" : "block",
        "updatetriggerobject" : "000000000000000b47c522b6f4c2b0ca508bd90bab59b73c7ef72432a88fc10e"
    }
]
```

Looking at updates for a simple send:

```
$ src/omnicore-cli omni_searchupdate 221efed5d6a492490ac951395159e3433e7d0f793fbfd7ffb4073df77e6874ab
[
    {
        "updatetype" : "balance",
        "updatedelta" : {
            "address" : "1Pr75FNvtoWHeocNfc4zTQCfK5kMVakWcn",
            "propertyid" : "2",
            "amount" : "-0.00010000",
            "balance" : "0.00080000",
            "reserved" : "0.00000000"
        },
        "updatesequencenumber" : 16758,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "221efed5d6a492490ac951395159e3433e7d0f793fbfd7ffb4073df77e6874ab"
    },
    {
        "updatetype" : "balance",
        "updatedelta" : {
            "address" : "1NyUe4gupjhvZYRPF8ZQk4m78UKJ7ij2GB",
            "propertyid" : "2",
            "amount" : "0.00010000",
            "balance" : "0.00010000",
            "reserved" : "0.00000000"
        },
        "updatesequencenumber" : 16759,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "221efed5d6a492490ac951395159e3433e7d0f793fbfd7ffb4073df77e6874ab"
    },
    {
        "updatetype" : "transaction",
        "updatedelta" : {
            "txid" : "221efed5d6a492490ac951395159e3433e7d0f793fbfd7ffb4073df77e6874ab",
            "fee" : "0.00010001",
            "sendingaddress" : "1Pr75FNvtoWHeocNfc4zTQCfK5kMVakWcn",
            "referenceaddress" : "1NyUe4gupjhvZYRPF8ZQk4m78UKJ7ij2GB",
            "ismine" : false,
            "version" : 0,
            "type_int" : 0,
            "type" : "Simple Send",
            "propertyid" : 2,
            "divisible" : true,
            "amount" : "0.00010000",
            "valid" : true,
            "blockhash" : "00000000000000015b56809828825816421fbf9cb53fab808633c5c6046992b5",
            "blocktime" : 1384535851,
            "block" : 269767,
            "confirmations" : 108073
        },
        "updatesequencenumber" : 16760,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "221efed5d6a492490ac951395159e3433e7d0f793fbfd7ffb4073df77e6874ab"
    }
]
```

Looking at updates for a MetaDEx trade:

```
$ src/omnicore-cli omni_searchupdate ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88
[
    {
        "updatetype" : "balance",
        "updatedelta" : {
            "address" : "1FEEpqdsTbQpKtnj4JWqaBYdCKBm9ty3ii",
            "propertyid" : "2",
            "amount" : "-1.00000000",
            "balance" : "0.21000000",
            "reserved" : "0.00000000"
        },
        "updatesequencenumber" : 193128,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88"
    },
    {
        "updatetype" : "balance",
        "updatedelta" : {
            "address" : "1HbWTBq4uZadEWndAWPATPMfZeFPtYjvNn",
            "propertyid" : "2",
            "amount" : "1.00000000",
            "balance" : "250.00088432",
            "reserved" : "0.00000000"
        },
        "updatesequencenumber" : 193129,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88"
    },
    {
        "updatetype" : "balance",
        "updatedelta" : {
            "address" : "1HbWTBq4uZadEWndAWPATPMfZeFPtYjvNn",
            "propertyid" : "2147483666",
            "amount" : "--1",
            "balance" : "4750",
            "reserved" : "8"
        },
        "updatesequencenumber" : 193130,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88"
    },
    {
        "updatetype" : "balance",
        "updatedelta" : {
            "address" : "1FEEpqdsTbQpKtnj4JWqaBYdCKBm9ty3ii",
            "propertyid" : "2147483666",
            "amount" : "1",
            "balance" : "1",
            "reserved" : "0"
        },
        "updatesequencenumber" : 193131,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88"
    },
    {
        "updatetype" : "metadextrade",
        "updatedelta" : {
            "txid" : "ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88",
            "address" : "1FEEpqdsTbQpKtnj4JWqaBYdCKBm9ty3ii",
            "propertyidreceived" : 2147483666,
            "amountreceived" : "1",
            "matchedtxid" : "243e1d05d7098c3da5decb823707b67d4f547eb0588f26f1847ace57df7a9907",
            "matchedaddress" : "1HbWTBq4uZadEWndAWPATPMfZeFPtYjvNn",
            "matchedpropertyidreceived" : 2,
            "matchedamountreceived" : "1.00000000"
        },
        "updatesequencenumber" : 193132,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88"
    },
    {
        "updatetype" : "metadexdelete",
        "updatedelta" : {
            "txid" : "243e1d05d7098c3da5decb823707b67d4f547eb0588f26f1847ace57df7a9907"
        },
        "updatesequencenumber" : 193133,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88"
    },
    {
        "updatetype" : "metadexcreate",
        "updatedelta" : {
            "address" : "1HbWTBq4uZadEWndAWPATPMfZeFPtYjvNn",
            "txid" : "243e1d05d7098c3da5decb823707b67d4f547eb0588f26f1847ace57df7a9907",
            "propertyidforsale" : 2147483666,
            "propertyidforsaleisdivisible" : false,
            "amountforsale" : "9",
            "amountremaining" : "8",
            "propertyiddesired" : 2,
            "propertyiddesiredisdivisible" : true,
            "amountdesired" : "9.00000000",
            "amounttofill" : "8.00000000",
            "action" : 1,
            "block" : 367542,
            "blocktime" : 1438203616,
            "index" : 642
        },
        "updatesequencenumber" : 193134,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88"
    },
    {
        "updatetype" : "transaction",
        "updatedelta" : {
            "txid" : "ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88",
            "fee" : "0.00006130",
            "sendingaddress" : "1FEEpqdsTbQpKtnj4JWqaBYdCKBm9ty3ii",
            "ismine" : false,
            "version" : 0,
            "type_int" : 25,
            "type" : "MetaDEx trade",
            "propertyidforsale" : 2,
            "propertyidforsaleisdivisible" : true,
            "amountforsale" : "1.00000000",
            "propertyiddesired" : 2147483666,
            "propertyiddesiredisdivisible" : false,
            "amountdesired" : "1",
            "unitprice" : "1.00000000000000000000000000000000000000000000000000",
            "valid" : true,
            "blockhash" : "00000000000000000a94ccba75e83f39017c425ceb7eeed98eca3fc3a5de4c67",
            "blocktime" : 1438651961,
            "block" : 368323,
            "confirmations" : 9517
        },
        "updatesequencenumber" : 193135,
        "updatetrigger" : "transaction",
        "updatetriggerobject" : "ba391fac4aed40e5fdd06d9698777e963d5cf39347f5e18e91abbdd9843e4e88"
    }
]
```

This is what's pushed out via the API connector.

The primary objective is to provide an API deployable by anyone, a more stable infrastructure for OmniChest's API and a simple alternative 'push' model with sequencing for integrators who are not having too much success with the 'pull' model querying with existing RPC commands.

This is all up in the air, does not yet have full coverage and may not go anywhere further than OmniChest, but I wanted to at least get it up here and start working back via GitHub again.

Thanks
Z

### CODE REVIEW

**Comment by dexX7** [comment]
Just.. wow! This is incredible!!

Before diving into it, a few higher level questions and notes:

1. Did you consider using Boost signals, instead of "hard calls"?

2. As far as I can see, the whole state is covered and tracked. This brings up the question, whether these signals may be used in combination, or as replacement of the old persistence layer? For example, whenever a trade is cancelled, the cancel is written via `recordMetaDExCancelTX`, but also via `APICreateMetaDExDeletionNotification`. Now in one case it looks like the actual data is stored, and in the other case a reference to the data (the txid), and I assume the txid is then used to lookup the actual data. Maybe this could be combined, in one way or another?

3. There seems to be an overlap with the JSON-RPC API, in terms of the construction of results. For example `PropertyToJSON` and `APICreatePropertyNotification` are pretty similar. The `API_Notification` calls appears to be more "object specific" or "atomic" (not sure, how to phrase this), but it's a very nice prepresentation of "primitives" (e.g. properties, trades, balances, ...). I could imagine that there were more calls like `XXXToJSON`, which might be shared between both APIs. What do you think?

In general, I love the concept! What gives me a bit of headache is the size and scope, since there are quite a few new things mixed together (a POSTer, new JSON conversions, the signals, a new DB). Do you think we could break this down into smaller pieces, which are integrated step by step?

**Comment by zathras-crypto** [comment]
> Just.. wow! This is incredible!!

Thanks dude, still some way to go but I wanted to move back to GitHub, I was feeling a little isolated hehe :)

> Did you consider using Boost signals, instead of "hard calls"?

I didn't nope - I really wanted to make sure sequencing would be accurate so kind of fell straight to "hard calls" though I guess even with signalling the message queue should still be processed in order.  What benefits would we gain from a switch? (aside from being able to hook in other listeners for those signals elsewhere in the code)

> As far as I can see, the whole state is covered and tracked

There are still missing bits (eg crowdsales) but it should be straight forward enough to add any bits I've missed.

> ...replacement of the old persistence layer...

Hehe you're on to me :P  It is an idea I have in mind yep, but early days :)  Basically I wanted to provide a model to store changes to the state that isn't coupled to anything specific.  Updates can be triggered by blocks & transactions currently, but we can add further triggers as needed.  With transactions also stored as an update to the state, we can eventually move away from the need to reparse them each time they are queried.

> There seems to be an overlap with the JSON-RPC API

Yeah there is probably quite a bit of overlap and some duplication in there - I agree methods should be shared where possible, I'll try to optimize on this front :)

> What gives me a bit of headache is the size and scope

Yep, understood - I'll try and break it down and make it more consumable, really that first commit was me staging a whole bunch of files from a couple different development boxes - leave it with me and I'll ping you when it's a bit more manageable! :)

**Comment by dexX7** [comment]
> Yep, understood - I'll try and break it down ...

I hope "this gives me headaches" didn't sound rude. :/ Where I was basically going: if we break it down, and consider each subpart isolated, then I believe we may resolve the redundant parts on the way.

As for a general outline, I could imagine to:

1. extract/add the JSON conversions (to a new `rpcconversions.cpp` or so)
2. see, if we can use the "conversion building blocks" for the old API, ideally ending up replacing the hardcoded conversions with `__ToJSON()` calls
3. add missing conversions, which may not be used right now by the old API, but needed for the new one
4. add hooks/signals for all relevant points (e.g. where `APIPost` is used right now), which might be noops at the beginning (because the POSTer isn't available yet)
5. add the new API/POSTer module
6. combine the hooks/signals with the new API endpoint

> What benefits would we gain from a switch? (aside from being able to hook in other listeners for those signals elsewhere in the code)

I kinda share the sentiment that hard calls seem more reliable and "directed", and for core code (e.g. the block/transaction handlers) it seems very suitable, but as you noted:

Signals allow to add multiple listeners, which may not be coupled at all, and it shifts the responsibility from the sender (say the consensus code) to the listener (say the API endpoint). Ideally the core shouldn't care, what role the listeners have, or whether there are listeners at all.

Another canidate as listener could be the logger, and if we accomplish that the core consensus code only has the actual code and signal hooks, then it would be a huge gain in my opinion, in terms of reducing the size of critical code, and "shielding"/isolating the core from non-consensus code.

> With transactions also stored as an update to the state, we can eventually move away from the need to reparse them each time they are queried.

You mentioned it yesterday with "the state is basically the result of a sequence of actions, and the sequence of updates may just be replayed". I'm not yet sure, if this is really feasible, but all this is *very* close and related to moving away from "one global state" to a much finer control. If we end up with creating representations for each update step, then we may potentially accomplish to be able to reconstruct the state for any point in time (e.g. "what is the state at block 1234?" -> "just apply all updates from 0 to n"). It's probably still a longer way to get to this point, but this PR bulldozes the way significantly! :)

For example, in the longer run, I could imagine to replace the "load_most_relevant_state()` calls with `replay_all_updates()`.

**Comment by dexX7** [comment]
Given this PR is outdated and needs further review, it's going to be closed for now.

**Pull request closed without merging**
