### PR TITLE
 Implement and switch to Feature-Activation-By-Message

### PR DESCRIPTION
**Pull request by zathras-crypto**
This PR serves to introduce the activation of features by broadcasting an activation message as opposed to the current methodology of hardcoded blockheights.

Note: Replaces #129

### CODE REVIEW

**Comment by dexX7** [comment]
So what about this?
```diff
@@ -153,8 +154,10 @@ bool CheckExpiredAlerts(unsigned int curBlock, uint64_t curTime)
                     bool txLive = (curBlock > (int64_t) expiryValue);
 
                     //testnet allows all types of transactions, so override this here for testing
-                    //txSupported = false; //testing
-                    //txLive = true; //testing
+                    if (isNonMainNet()) {
+                        txSupported = true; //testing
+                        //txLive = true; //testing
+                    }
```

**Comment by dexX7** [comment]
I reverted the activation height for the MetaDEx in regtest mode via 78bac14e0fbd17cbd64e5fd26788283761d233f0, because the tests otherwise break.

**Comment by zathras-crypto** [comment]
> So what about this?

Ahh sorry should have added the WIP tag...

Basically I had in mind to revert that, and move alerting to a standardized payload as suggested in another thread - which would then mean the test alert for tx99 causing the abort would not be processed in 0.0.10 based code...

**Comment by dexX7** [comment]
Haha, this is brilliant. I like it! :)

**Pull request merged**
