### PR TITLE
Fix too-aggressive database clean in reorg event

### PR DESCRIPTION
**Pull request by zathras-crypto**
I found during testing reorgs that the trade DB is cleared one block too far in the event a chain reorg occurs.

* Block 101 : Trade ABC
* Block 102 : Trade DEF
* Block 102 is disconnected and a new block is mined.

The ```deleteAboveBlock()``` calls execute, and trade DEF is correctly deleted from the trades database.  Unfortunately so is trade ABC.  

The cause is related to the whether the ```deleteAboveBlock()``` calls are inclusive.  This PR fixes the issue above, standardizes the behaviour of the corresponding function for the STO database, and updates the commenting to make things a bit clearer.

### CODE REVIEW

**Comment by zathras-crypto** [comment]
Should have mentioned, not consensus affecting (these databases are used to provide history on the RPC layer).

**Comment by dexX7** [comment]
Interesting, and very good catch!

We have reorg tests for STO, so I'm very curious what happens here.

**Comment by zathras-crypto** [comment]
>Interesting, and very good catch!

Thanks, I picked it up in my latest tests fixing up fee rollbacks (https://github.com/OmniLayer/omnicore/pull/359/commits/083d80e691424232475ffdfc30aa6f980d5c77a3)... 

>We have reorg tests for STO, so I'm very curious what happens here.

Awesome :)  The code change shouldn't be a behaviour change, it'll be interesting to see!

**Comment by dexX7** [comment]
>  The code change shouldn't be a behaviour change, it'll be interesting to see!

How is that? How can it not be a behavior change?

**Comment by dexX7** [comment]
Only the MetaDEx unit test related tests failed during the CI run, so the STO reorg tests pass.

It's not yet clear to me: is there a blind spot, and the initial behavior, which was fixed, can be tested?

We actually have a test "Historical STO transactions are not affected by reorganizations", which creates two STOs, reverts the last one, and confirms the effect of the first one is still valid:

https://github.com/OmniLayer/OmniJ/blob/master/omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SendToOwnersReorgSpec.groovy#L108

**Comment by zathras-crypto** [comment]
> How is that? How can it not be a behavior change?

This is for the STO database.  Let's say nHeight = 100.

*Before:*
Called ```deleteAboveBlock()``` with nHeight -1, check uses <=
Eg : ```if (block_of_record <= 99)```
*After:*
Called ```deleteAboveBlock()``` with nHeight, check uses <
Eg : ```if (block_of_record < 100)```

Is the phrasing I used bad practice?

**Comment by zathras-crypto** [comment]
> It's not yet clear to me: is there a blind spot, and the initial behavior, which was fixed, can be tested?

Sure, build without this patch, spin up regtest, execute a trade, mine a block, execute another trade, mine another block, roll back the chain one block.

If you check omnicore.log you'll see that both trades were deleted from the trades database instead of just the second one.

Sorry I did have a bash regtest script for this but I forgot to copy it before I butchered it for a different test :(

**Comment by zathras-crypto** [comment]
> We actually have a test "Historical STO transactions are not affected by reorganizations"

I love the quality of these tests, that's fantastic :)

**Comment by dexX7** [comment]
> This is for the STO database.

Ahh, I see. So there was only an issue with the MetaDEx database, and the submission also adjusts the behavior of the STODB, so it's the same for all. Now I got it.. hehe. :)

> Sorry I did have a bash regtest script for this but I forgot to copy it before I butchered it for a different test :(

No worries, and no need. It's clear to me now. I was just wondering, whether the STO test linked above could be faulty.

As a note to myself: would be useful to do automated reorg tests for the MetaDEx also. :)

**Comment by dexX7** [comment]
I tested this PR locally once more, and it's all good. Thanks!

**Pull request merged**
