### PR TITLE
Bump version to Omni Core 0.0.11-rel

### PR DESCRIPTION
**Pull request by dexX7**
This pull request updates the version to `0.0.11-rel` and adds the last pieces of the change log.

### CODE REVIEW

**Comment by zathras-crypto** [comment]
I think we need to increment the version too mate, otherwise we can't exclude rc1 from the minimum client version when we activate STO v1.

**Comment by dexX7** [comment]
Very, very good point! I pushed a fix for this via e0c3156a1ce36c1e72cc4d3135a7c0916bd235bf, which increments the "build" part of our version number. This part is not included in the version string (e.g. 0.0.11.0), and should not be included in the file names either.

Given that our version scheme is a bit messed up, it would be awesome, if you could confirm that we can get away with this.

**Comment by zathras-crypto** [comment]
> Given that our version scheme is a bit messed up, it would be awesome, if you could confirm that we can get away with this.

I'll prep a test to double check :)

Also completely unrelated, but which field were you using to search on 'Chest that isn't trimming properly?  Is it the search bar at the top or one of the actual search pages?

Thanks
Z

**Comment by dexX7** [comment]
> Is it the search bar at the top or one of the actual search pages?

Was the search bar on the top-right.

**Comment by zathras-crypto** [comment]
> Was the search bar on the top-right.

Thanks for this!  I didn't really understand until I actually tried it lol.  That input is trimmed already which is why I didn't see the problem.  So what happens is the value supplied in that field is evaluated for its length, and then that length is used to take a best guess at whether to lookup a property ID, TXID or address.  The problem was that the trimming was being done *after* the length was evaluated, so for example an address with whitespace had a length >35, which 'Chest thinks is too long to be an address.

Easy fix, the input is now trimmed (and sanitized for special characters) before evaluating the length and it seems to be working properly now.

On the topic of 'Chest, hopefully it should feel a little faster now with some new changes I've made to way tables are indexed to lower API resource consumption.

> Given that our version scheme is a bit messed up, it would be awesome, if you could confirm that we can get away with this.

Yep, tested & seems fine.  OK to merge.

Activating with a min client version of 1100001 against a build that includes this PR works fine:
```
Preparing a test environment...
   * Starting a fresh regtest daemon
   * Preparing some mature testnet BTC
   * Obtaining a master address to work with
   * Funding the address with some testnet BTC for fees
   * Participating in the Exodus crowdsale to obtain some OMNI
   * Creating an indivisible test property
   * Creating a divisible test property
   * Generating addresses to use
   * Seeding mpJr9PME1TZTGHNeqwUVuMpuoPundDKKqq with SP#3

Testing a cross property (v1) STO
   * Executing the transaction
   * Verifiying the results
     # Checking the STO transaction was invalid (feature not yet activated)... PASS
Activating cross property (v1) Send To Owners...
   * Sending the activation (min client 1100001)
     # Checking the activation transaction was valid... PASS
   * Mining 10 blocks to forward past the activation block
     # Checking the activation went live as expected... PASS
Testing a cross property (v1) STO
   * Executing the transaction
   * Verifiying the results
     # Checking the STO transaction was valid... PASS

####################
#  Summary:        #
#    Passed = 4    #
#    Failed = 0    #
####################
```

As desired the same activation with the same min client version fails on RC2:
```
Preparing a test environment...
   * Starting a fresh regtest daemon
   * Preparing some mature testnet BTC
   * Obtaining a master address to work with
   * Funding the address with some testnet BTC for fees
   * Participating in the Exodus crowdsale to obtain some OMNI
   * Creating an indivisible test property
   * Creating a divisible test property
   * Generating addresses to use
   * Seeding mzawPv2mvaiMjc9mVtRx3vs6eVDiYBis2J with SP#3

Testing a cross property (v1) STO
   * Executing the transaction
   * Verifiying the results
     # Checking the STO transaction was invalid (feature not yet activated)... PASS
Activating cross property (v1) Send To Owners...
   * Sending the activation (min client 1100001)
     # Checking the activation transaction was valid... PASS
   * Mining 10 blocks to forward past the activation block
Error: Shutting down due to unsupported feature activation (10: Cross-property Send To Owners)
     # Checking the activation went live as expected...
error: couldn't connect to server
```

**Pull request merged**
