### PR TITLE
Fix and update seed blocks

### LINKED ISSUE #319: Seed blocks need updating for 380000 to 390000
Block 390000 has passed, seed blocks should be updated.

### LINKED ISSUE #322: Seed blocks from 370000 to 380000 are not used
```const int MAX_SEED_BLOCK = 369999;``` in ```seedblocks.cpp``` causes seed blocks 370000 to 380000 to be ignored and every block in the range to be checked.

A verification should be performed that the seed blocks are accurate for this range.

### PR DESCRIPTION
**Pull request by zathras-crypto**
- Fixes MAX_SEED_BLOCK value (now set to 390000)
- Fixes incorrect seed blocks between 370000 and 380000
- Adds seed blocks between 380000 and 390000
- Passes checkpoints (obtained without seed block filter)

edit from @dexX7 to auto-close related  issues: resolves #319, resolves #322.

### CODE REVIEW

**Comment by dexX7** [comment]
> This branch is out-of-date with the base branch

**Comment by zathras-crypto** [comment]
> This branch is out-of-date with the base branch

Yeah, I messed up a little and hadn't updated my local branch, which also meant I wasn't actually verifying against the new 390,000 checkpoint (which turned up another seed block issue).

Fixed up & corrected, just running a testing pass now and then will push :)

**Comment by dexX7** [comment]
> which turned up another seed block issue

Could you roughly outline how you generated them this time?

**Comment by zathras-crypto** [comment]
OK, that should be it now - rebased and sorted the remaining seed block issues :)

To test, I use ```consensus_hash_every_block``` debug option and compare results from this PR vs disabled seed block filter.

> Could you roughly outline how you generated them this time?

Sure - I cheated hehe...  The hooks I was using were hacky and seemed to give bad results, so I just used Chest's database instead this time around...  FYI I intend to revisit the upgraded consensus hashing PR and include in it the ability to generate seed block lists directly over RPC by querying levelDB so we've got a defined and re-usable process (to be honest I found this whole thing very long winded, manual and error prone this time - I don't remember it being like that last time I did it, but that's probably why last time's results were faulty!  So having a coded up process for seed block generation along with a more in-depth checkpointing will make me feel a bit better about using seed blocks).

**Comment by zathras-crypto** [comment]
Note, seed blocks 370,000 to 390,000 also pass checkpoints with the upgraded consensus hashing system.  I'd like to add in the issuer address to the property data hashed and give it one more run through just to triple check before we merge.

**Comment by dexX7** [comment]
> to be honest I found this whole thing very long winded, manual and error prone this time - I don't remember it being like that last time I did it, but that's probably why last time's results were faulty!

If I'm not mistaken, then we both created seedblock lists and ended up with different results (mostly related to structurally valid/invalid IIRC etc.) and I manually added hooks and whatnot. :)

Having a more easy and straight forward way to deal with this would definitely be a big win!

> I'd like to add in the issuer address to the property data hashed and give it one more run through just to triple check before we merge.

Please let me know once this is good to go. I'm currently still unable to test it myself, but given the effort and testing, I'm fine with a merge, especially given that the CI server also provides additional feedback (and checkpoint tests) due to the reparsing. :)

**Comment by zathras-crypto** [comment]
Quick note, this is good to go.  I've verified the seed block lists using the new consensus hashing upgrades and it all still passes, so if there is still something amiss I'm unable to spot it :)

**Comment by dexX7** [comment]
Sorry, once again:

> This branch is out-of-date with the base branch

~.~

**Comment by zathras-crypto** [comment]
> This branch is out-of-date with the base branch

Sorry, rebased :)

**Comment by dexX7** [comment]
Yeah, I really start to believe we should disable this check.. it's kinda annoying and stops the flow.

I'm going to merge this one, and then #327 (which has to be rebased then too..).

**Pull request merged**
