### PR TITLE
Add MetaDEx guide documentation

### PR DESCRIPTION
**Pull request by zathras-crypto**

### CODE REVIEW

**Comment by zathras-crypto** [comment]
Merging as documentation only (no code impact)

**Comment by dexX7** [comment]
Why would you black out testnet addresses, which were created as part of this tutorial?

**Comment by zathras-crypto** [comment]
He he :) because I used them on various faucets while travelling from very
traceable IPs :p - just habit perhaps!!!

**Comment by dexX7** [comment]
I think this document should be moved to `src/omnicore/doc`.

**Comment by zathras-crypto** [comment]
> I think this document should be moved to src/omnicore/doc.

I agree, but the link has been shared in numerous places as far as I know & moving it would invalidate the link (not that I'm seeing much testing still, but I don't know what else to do to encourage that other than asking Patrick whether he wants to offer dev MSC as bounty for testing and finding bugs) anyway back to topic; perhaps we leave it where it is temporarily and make sure to move it prior to release candidate 0.0.10?

**Comment by dexX7** [comment]
> perhaps we leave it where it is temporarily and make sure to move it prior to release candidate 0.0.10?

Sounds good.

**Pull request merged**
