### PR TITLE
Automate state refresh on client version change when needed

### PR DESCRIPTION
**Pull request by zathras-crypto**
Note: increment DB_VERSION definition along with changes that require repopulating databases (reparsing) to ensure clients only use a database compatible with their codebase.

### CODE REVIEW

**Comment by dexX7** [comment]
That's very useful!

I'm wondering though, if the version might be included directly in the DB classes (either in the child class(es) like `CMPTxList`, or in the base class `CDBBase`). The check might also be done when opening the DB (e.g. `CDBBase::Open()`), and an auto-wipe could be triggered, if there is a version mismatch, or the version field is missing. The downside: I'm not really sure how to extract meaningful information about the initialization. Rephrased: we could probably auto-wipe on version mismatches, but then we still somehow need to signal to the rest of the program that it happened.

**Comment by dexX7** [comment]
On the other hand, let's assume we'd wipe the `CMPSPInfo` DB before calling `load_most_relevant_state()`, then there won't be any watermark, and as result the state is also resetted. Feels a bit like a workaround though.

My primary hesitation right now is that I think it could be pretty error prone, if the version has to be set and compared manually. Say for example, when clearing via `clear_all_state()`.

**Comment by zathras-crypto** [comment]
Thanks for the quick review!

> My primary hesitation right now is that I think it could be pretty error prone, if the version has to be set and compared manually. Say for example, when clearing via clear_all_state().

Could you clarify mate what you mean by error prone if we compare manually?  When clear_all_state() clears the DBs it then writes the client current DB version into the cleared DBs.

**Comment by dexX7** [comment]
Sorry, my connection is lost for some reason, probably due to maintanence.  I'm online for a moment via mobile.

In short: ACK, because I also don't see a better alternative at the moment, and the PR resolves the initial issue as intended.

**Comment by dexX7** [comment]
> Could you clarify mate what you mean by error prone if we compare manually?

I can't really find the right words - if the version check/set stuff happens implicitly, and doesn't need extra commands that one should be aware of.

From a higher level perspective:

- it's fine to handle version checks during the initialization
- it's not ideal that it is also necessary in other parts

Let's take a look for example at what happens, if `fReindex` is set: the DBs are wiped, but `startClean` isn't set, so `setDBVersion()` isn't called immediently, and the `wrongDBVersion` path not executed. At some point later, indirectly via `clear_all_state()`, the version is finally set though.

It has the same effect, and works nevertheless though, but it's not really intuitive imho.

Here is another idea, which is also not really intuitive, but maybe it provides you new ideas: currently the watermark block is stored with the key `'B'`. What if we change that `'B'` to `'C'? We'd solve the issue that explicit commands must be used to check the "version", but it's even less transparent.

I'll leave the PR open for another few hours, or a day, and if nothing new pops up, we'll merge. Deal? :)

**Comment by dexX7** [comment]
@zathras-crypto: there is something fishy, and it took me some time to get down to it.

When I run the regtests with v0, shutdown and start clean, then:
```
2897 transactions processed, 1460 meta transactions found
```
```
$ ./src/omnicore-cli omni_getinfo
{
    "mastercoreversion" : "0.0.9.99-dev",
    "bitcoincoreversion" : "0.10.2",
    "commitinfo" : "5066b6f-dirty",
    "block" : 1040,
    "blocktime" : 1440115932,
    "blocktransactions" : 1,
    "totaltrades" : 108,
    "totaltransactions" : 1313,
    "alert" : {
    }
}
```
When I then switch to v1, the reprocessing is triggered, however:
```
2897 transactions processed, 451 meta transactions found
```
```
$ ./src/omnicore-cli omni_getinfo
{
    "mastercoreversion" : "0.0.9.99-dev",
    "bitcoincoreversion" : "0.10.2",
    "commitinfo" : "5066b6f-dirty",
    "block" : 1040,
    "blocktime" : 1440115932,
    "blocktransactions" : 1,
    "totaltrades" : 0, // <---
    "totaltransactions" : 1313,
    "alert" : {
    }
}
```

And worse, dumping balances gives also different results.

During the v0 -> v1 processing there are a lot of rejection messages in the log, and the interesting part, where both logs (v0, v1) start to differ:

v0:
```
CREATED FIXED PROPERTY id: 3
recordTX(d1863d60c521b26e714b0f378a515c15d9ced8cea5b1ffa6c91f30a740b7d15a, valid=YES, block= 144, type= 50, value= 1123581321345589)
```
v1:
```
CREATED FIXED PROPERTY id: 49
recordTX(d1863d60c521b26e714b0f378a515c15d9ced8cea5b1ffa6c91f30a740b7d15a, valid=YES, block= 144, type= 50, value= 1123581321345589)
```

See, what's going on? ;)

**Comment by dexX7** [comment]
The issue is partially related to the order of initiailzations:

```c++
1. _my_sps = new CMPSPInfo(GetDataDir() / "MP_spinfo", fReindex);
2. bool wrongDBVersion = (p_txlistdb->getDBVersion() != DB_VERSION); // wrong due to upgrade
3. nWaterlineBlock = load_most_relevant_state();
4. nWaterlineBlock = -1; // due to wrong version
5. clear_all_state(); // due to waterline
6. msc_initial_scan(nWaterlineBlock);
7. ...
```

But the actual underlying issue is pretty deep and I'm very, very glad we found it.

`CMPSPInfo` is basically *almost* only a LevelDB with some query methods, and while it also holds the hardcoded for MSC/TMSC, there are two other class properties:

```c++
uint32_t next_spid;
uint32_t next_test_spid;
```

When we `clear_all_state()`, and as consequence `_my_sps->Clear()`, the database is wiped as intended, but those "next property identifier hints" are not resetted.

**Comment by zathras-crypto** [comment]
Thanks for all the great feedback dude, looks like you found quite a significant issue... Looking into it now - if we reset ```next_spid``` and ```next_test_spid``` on ```clear_all_state()``` does that resolve the issue?  Given you found these there are probably other variables that may need clearing within the ```clear_all_state()``` function...

**Comment by dexX7** [comment]
Yes, this should do the trick, or alternatively something like:
```diff
diff --git a/src/omnicore/sp.cpp b/src/omnicore/sp.cpp
index 4c564f0..c91bc87 100644
--- a/src/omnicore/sp.cpp
+++ b/src/omnicore/sp.cpp
@@ -90,6 +90,14 @@ CMPSPInfo::~CMPSPInfo()
     if (msc_debug_persistence) PrintToLog("CMPSPInfo closed\n");
 }
 
+void CMPSPInfo::Clear()
+{
+    // wipe database via parent class
+    CDBBase::Clear();
+    // reset "next property identifiers"
+    init();
+}
+
 void CMPSPInfo::init(uint32_t nextSPID, uint32_t nextTestSPID)
 {
     next_spid = nextSPID;
diff --git a/src/omnicore/sp.h b/src/omnicore/sp.h
index a3c59d1..8dddeb8 100644
--- a/src/omnicore/sp.h
+++ b/src/omnicore/sp.h
@@ -139,6 +139,8 @@ private:
 public:
     CMPSPInfo(const boost::filesystem::path& path, bool fWipe);
     virtual ~CMPSPInfo();
+    /** Extends clearing of CDBBase. */
+    void Clear();
 
     void init(uint32_t nextSPID = 0x3UL, uint32_t nextTestSPID = TEST_ECO_PROPERTY_1);
 
```

**Comment by dexX7** [comment]
This issue is pretty bad, and it completely shreds the whole consensus apart, because all property identifiers are shifted, if this happens (potentially anytime when `clear_all_state()` is called).

We have reorg tests (where the state is cleared more than once), and in one of the tests the property identifiers are also checked, to guard against something like this..

So how comes, we never ever had any issues? Because the state of the last 50 blocks is persisted, and when restored, the "next identifiers" are also updated.

In practise this means: reorgs with more than 50 blocks are devastating for unpatched versions, which is fortunally very rare to nearly impossible. On the other hand, the [fork in March 2013](https://bitcoinmagazine.com/3668/bitcoin-network-shaken-by-blockchain-fork/) caused a 24 block deep reorganization, so this is definitely nothing that should be hand waived.

**Comment by zathras-crypto** [comment]
I like the patch, that's a better way to come at the problem...

> In practise this means: reorgs with more than 50 blocks are devastating for unpatched versions

So you mean if there was a reorg with more than 50 blocks (yikes, but feasible) there would be no state to load, so ```clear_all_state()``` would be called, but the ```next_spid``` & ```next_test_spid``` values would not have been reset, so all property ID's would be out?

Yeah - that would 'shred' consensus to pieces !!!  Ouch...

**Comment by zathras-crypto** [comment]
> it's not ideal that it is also necessary in other parts

I agree, but clearing the state happens in other parts, which means we inherently have to rewrite the version.  That is unless of course we don't store the version as part of the state and store it elsewhere, but that kind of defeats the purpose (having a state version tied to client version).

**Comment by dexX7** [comment]
> So you mean ...

Yeah, I think so, hehe. Here is a small test, which can be run quickly from the console:

1. set `regtest=1` in your `bitcoin.conf`
2. clear/rm `~/.bitcoin/regtest`
3. start `omnicored` or `omnicore-qt`
4. paste/execute the following lines in the console (the paths may need to be adjusted):
```
./src/omnicore-cli setgenerate true 101
ADDR=$(./src/omnicore-cli getnewaddress)
./src/omnicore-cli sendtoaddress $ADDR 1.0
./src/omnicore-cli setgenerate true 60
./src/omnicore-cli omni_sendissuancemanaged $ADDR 1 1 0 "" "" "Expected ID: 3" "" ""
./src/omnicore-cli omni_sendissuancemanaged $ADDR 1 1 0 "" "" "Expected ID: 4" "" ""
./src/omnicore-cli omni_sendissuancemanaged $ADDR 1 1 0 "" "" "Expected ID: 5" "" ""
./src/omnicore-cli setgenerate true 1
./src/omnicore-cli omni_listproperties
BLOCK=$(./src/omnicore-cli getblockhash 105)
./src/omnicore-cli invalidateblock $BLOCK
./src/omnicore-cli clearmempool
./src/omnicore-cli setgenerate true 1
./src/omnicore-cli omni_listproperties
./src/omnicore-cli omni_sendissuancemanaged $ADDR 1 1 0 "" "" "Expected ID: 3 (not 6)" "" ""
./src/omnicore-cli omni_sendissuancemanaged $ADDR 1 1 0 "" "" "Expected ID: 4 (not 7)" "" ""
./src/omnicore-cli omni_sendissuancemanaged $ADDR 1 1 0 "" "" "Expected ID: 5 (not 8)" "" ""
./src/omnicore-cli setgenerate true 1
./src/omnicore-cli omni_listproperties
```

**Comment by dexX7** [comment]
> I agree, but clearing the state happens in other parts, which means we inherently have to rewrite the version. That is unless of course we don't store the version as part of the state and store it elsewhere, but that kind of defeats the purpose (having a state version tied to client version).

Well, I agree with the current proposal, this is currently a somewhat good solution, and it's a great improvement, which ultimately lead to my approval of this PR.

But where I was going was something similar like the issue with the next property identifiers now showed: unless one knows that the version has to be set after clearing the DB (or related), or notices it, it's not intuitive, and it can easily be overlooked.

In this case (the version setting) it's absolutely harmless, and I also don't see a better alternative, but you probably see what I mean?

**Comment by zathras-crypto** [comment]
> unless one knows that the version has to be set after clearing the DB (or related), or notices it, it's not intuitive, and it can easily be overlooked.

Yeah, I see your point - but for clarity that's why I wanted setting the version within the ```clear_all_state()``` function, because that should be our 'go to' for resetting the state.  

Ideally we would never manually clear a DB (especially individually) and we would use a single central function to wipe state & history - that's what I thought ```clear_all_state()``` was for :)

Long story short, I think we should have only one place to "clear the state", and that same place should be responsible for writing out the version to a new/fresh state.

> But where I was going was something similar like the issue with the next property identifiers now showed

Yeah this is a fantastic catch (thanks!!!!!), but I don't see it as a problem with the state version methodology.  I just see it as a more of a generic problem that ```clear_all_state()``` doesn't do a good enough job of clearing the state (because it leaves variables around uncleared from the previous state)

> Well, I agree with the current proposal, this is currently a somewhat good solution, and it's a great improvement, which ultimately lead to my approval of this PR.

Thanks :)  I'm open to better ways to do it though of course :)

**Comment by dexX7** [comment]
> but for clarity that's why I wanted setting the version within ... because that should be our 'go to' for resetting the state. ... Ideally we would never manually clear a DB

Yeah, that's a very good point, I'm convinced. :)

I quickly went through the other DBs and they are solely DBs with methods, so the clearing is covered. The only other maybe relevant globals I've seen so far are caches.

I suggest you include the fix for `CMPSPInfo`, and we consider the PR is final? Primarily it should tackle the DB version, which it does, and potentially optimizing other parts could be done separately, if needed.

**Comment by zathras-crypto** [comment]
> Yeah, I think so, hehe. Here is a small test

Oh dude, that is just heinous - great find - I wonder if there is anything else ```clear_all_state()``` should be clearing but is not...  I'll have a nose around...

Without patch:
```
[
    {
        "propertyid" : 1,
        "name" : "MasterCoin",
        "category" : "N/A",
        "subcategory" : "N/A",
        "data" : "***data***",
        "url" : "www.mastercoin.org",
        "divisible" : true
    },
    {
        "propertyid" : 2,
        "name" : "Test MasterCoin",
        "category" : "N/A",
        "subcategory" : "N/A",
        "data" : "***data***",
        "url" : "www.mastercoin.org",
        "divisible" : true
    },
    {
        "propertyid" : 6,
        "name" : "Expected ID: 3 (not 6)",
        "category" : "",
        "subcategory" : "",
        "data" : "",
        "url" : "",
        "divisible" : false
    },
    {
        "propertyid" : 7,
        "name" : "Expected ID: 4 (not 7)",
        "category" : "",
        "subcategory" : "",
        "data" : "",
        "url" : "",
        "divisible" : false
    },
    {
        "propertyid" : 8,
        "name" : "Expected ID: 5 (not 8)",
        "category" : "",
        "subcategory" : "",
        "data" : "",
        "url" : "",
        "divisible" : false
    }
]
```

With patch:
```
[
    {
        "propertyid" : 1,
        "name" : "MasterCoin",
        "category" : "N/A",
        "subcategory" : "N/A",
        "data" : "***data***",
        "url" : "www.mastercoin.org",
        "divisible" : true
    },
    {
        "propertyid" : 2,
        "name" : "Test MasterCoin",
        "category" : "N/A",
        "subcategory" : "N/A",
        "data" : "***data***",
        "url" : "www.mastercoin.org",
        "divisible" : true
    },
    {
        "propertyid" : 3,
        "name" : "Expected ID: 3 (not 6)",
        "category" : "",
        "subcategory" : "",
        "data" : "",
        "url" : "",
        "divisible" : false
    },
    {
        "propertyid" : 4,
        "name" : "Expected ID: 4 (not 7)",
        "category" : "",
        "subcategory" : "",
        "data" : "",
        "url" : "",
        "divisible" : false
    },
    {
        "propertyid" : 5,
        "name" : "Expected ID: 5 (not 8)",
        "category" : "",
        "subcategory" : "",
        "data" : "",
        "url" : "",
        "divisible" : false
    }
]
```

**Comment by zathras-crypto** [comment]
> I suggest you include the fix for CMPSPInfo, and we consider the PR is final? Primarily it should tackle the DB version, which it does, and potentially optimizing other parts could be done separately, if needed.

Yep, patch is in :)

> I quickly went through the other DBs and they are solely DBs with methods, so the clearing is covered. The only other maybe relevant globals I've seen so far are caches.

Awesome thanks - even caches should be cleared (I kind of err on the side of caution and think "clean everything" hehe) but that's not relevant to this PR, I can open another one to address clearing leftover data in ```clear_all_state()```.

**Comment by dexX7** [comment]
> I kind of err on the side of caution and think "clean everything" hehe) but that's not relevant to this PR, I can open another one to address clearing leftover data in clear_all_state()

Yeah, sure! Haha, please tell me, if I'm too niggling!  :) I mentioned it, because I had the contributions guidelines in mind, which are currently WIP, and these two points may apply here:

- 26. unrelated changes should be split into more than one submission (that's pretty straight forward I think)
- 43. maintainers should not ask for improvements that are not directly related to the PR (i.e. user intended to fix a type, we request for a full blown refactor ... pretty annoying probably)

**Pull request merged**
