### PR TITLE
Add payload creation to the RPC interface

### PR DESCRIPTION
**Pull request by zathras-crypto**
This PR adds support for payload creation via the RPC interface.  The calls are similar to the send transactions, without the requirement for an address or any of the balance checks.

This allows an integrator building transactions via the raw transactions interface to generate the payload via Omni Core.

The internal ```CreatePayload_function``` calls are used and the parameters are largely taken from the equivalent calls to send each type of transaction.

Note: this is to compliment calls such as ```omni_createraw_opreturn``` where a payload needs to be supplied.

### CODE REVIEW

**Comment by zathras-crypto** [comment]
Also, I left in some sanity checks (eg whether a property being used exists etc) - I'm of split minds on whether we should make the payload creation API completely free of state based checks.

**Comment by zathras-crypto** [comment]
Oh, and sorry - completely missed the requirement for this in the PR description...

In a nutshell we need to provide payloads when using the raw transactions interface.  The initial requirement was raised by Tomas & Adam for OmniWallet, where they would like to delegate payload generation to Omni Core as they're using the raw transactions interface.  Additionally this is also useful for the new OmniChest transaction builder - I'm doing payloads in my own library right now but it seems wasteful to duplicate and keep a separate library updated when Omni Core already has payload generation capabilities (they just weren't exposed over RPC until now).

Regarding 0.12, I figure that's not quite there yet and this is something we'd like to run in production ASAP hence the basing on 0.0.10 where we can feel pretty comfortable with the build.

Thanks
Z

**Comment by dexX7** [comment]
Wow, this is awesome!

Will test it throughout the day.

**Comment by dexX7** [comment]
> Also, I left in some sanity checks (eg whether a property being used exists etc) - I'm of split minds on whether we should make the payload creation API completely free of state based checks.

I'd prefer having no checks here, given that the raw transaction API is pretty low level and "for advanced users".

**Pull request merged**
