### PR TITLE
Protect uint256 plain integer math

### LINKED ISSUE #408: Random Crash
Hey Guys, 
 Just ran into the following random crash. Here's the last few lines from the log for reference. Client is restarting now

```
ERROR: AcceptToMemoryPool : free transaction rejected by rate limiter
UpdateTip: new best=0000000000000000037d3ff27b42c1a7480e77f36feffce5ef10ae892db87085  height=422775  log2_work=85.055898  tx=145657629  date=2016-07-29 16:59:04 progress=1.000001  cache=31869
2016-07-29 16:55:44 ____________________________________________________________________________________________________________________________________
2016-07-29 16:55:44 parseTransaction(block=422775, 2016-07-29 16:59:04 idx= 8); txid: a23ca91f914b327e1148d7dbc2b034b0ab7bb3a3da3a7cfaf84ab353cf568a77
2016-07-29 16:55:44     ------------------------------
2016-07-29 16:55:44              version: 0, class C
2016-07-29 16:55:44                 type: 0 (Simple Send)
2016-07-29 16:55:44             property: 31 (SP token: 31)
2016-07-29 16:55:44                value: 36.40965376
2016-07-29 16:55:44 update_tally_map(1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw, 31=0x1F, -3640965376, ttype=0): before=270795127823236, after=270791486857860
2016-07-29 16:55:44 update_tally_map(31weU6dZWWdRSMjsjCi5iUHCdopDuZZBp2, 31=0x1F, +3640965376, ttype=0): before=76029030, after=3716994406
2016-07-29 16:55:44 recordTX(a23ca91f914b327e1148d7dbc2b034b0ab7bb3a3da3a7cfaf84ab353cf568a77, valid=YES, block= 422775, type= 0, value= 3640965376)
2016-07-29 16:55:44 ____________________________________________________________________________________________________________________________________
2016-07-29 16:55:44 parseTransaction(block=422775, 2016-07-29 16:59:04 idx= 22); txid: b8d6f504b466e12744f43b70c9737a990179c681b1dc0cc05e950efddc29bd76
2016-07-29 16:55:44     ------------------------------
2016-07-29 16:55:44              version: 0, class C
2016-07-29 16:55:44                 type: 22 (DEx Accept Offer)
2016-07-29 16:55:44             property: 1 (OMNI)
2016-07-29 16:55:44                value: 0.10000000
2016-07-29 16:55:44 DEx_acceptCreate: found a matching sell offer [seller: 1LF4uhCxwoZ6kbdDznMiqFSoqGxdGQGGQC, buyer: 1GoiNJaMc4ykrDrp7pbntfjRsCu4LX3wAW, property: 1)
2016-07-29 16:55:44 update_tally_map(1LF4uhCxwoZ6kbdDznMiqFSoqGxdGQGGQC, 1=0x1, -10000000, ttype=1): before=10000000, after=0
2016-07-29 16:55:44 update_tally_map(1LF4uhCxwoZ6kbdDznMiqFSoqGxdGQGGQC, 1=0x1, +10000000, ttype=2): before=0, after=10000000
2016-07-29 16:55:44 CMPAccept(10000000): cc504b3da859d479ab9ba33baa7efa8f12206483b6eb034bd9c1910c57b25e63
2016-07-29 16:55:44 recordTX(b8d6f504b466e12744f43b70c9737a990179c681b1dc0cc05e950efddc29bd76, valid=YES, block= 422775, type= 22, value= 10000000)
ERROR: AcceptToMemoryPool : nonstandard transaction: dust
ERROR: AcceptToMemoryPool : nonstandard transaction: dust
ERROR: AcceptToMemoryPool : free transaction rejected by rate limiter
ERROR: AcceptToMemoryPool : nonstandard transaction: dust
ERROR: AcceptToMemoryPool : nonstandard transaction: dust
ERROR: AcceptToMemoryPool : free transaction rejected by rate limiter
ERROR: AcceptToMemoryPool : nonstandard transaction: dust
ERROR: AcceptToMemoryPool : nonstandard transaction: dust
keypool reserve 2
keypool return 2
omnicored: ./omnicore/uint256_extensions.h:48: int64_t mastercore::ConvertTo64(const uint256&): Assertion `number <= uint256_const::max_int64' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by dexX7**
Currently there may be an overflow-ish issue when dividing and rounding up certain numbers.

This pull request adds a test for this case, and protects against it, by expecialy checking, wheter the numerator is zero.

This resolves #408.

### CODE REVIEW

**Comment by zathras-crypto** [comment]
The approach of returning a straight zero when the numerator is zero seems sound.

Confirming discussions on Slack:

* without the patch I get
```
inputvalues (offered, desired, available) = 100000000, 10000, 0  
amountOffered256 = 0000000000000000000000000000000000000000000000000000000005f5e100  
amountDesired256 = 0000000000000000000000000000000000000000000000000000000000002710  
amountAvailable256 = 0000000000000000000000000000000000000000000000000000000000000000  
amountDesired256 after DivideAndRoundUp = 0000002af31dc4611873bf3f70834acdae9f0f4f534f5d60585a5f1c1a3ced1c0000002af31dc4611873bf3f70834acdae9f0f4f534f5d60585a5f1c1a3ced1c
```

* with the patch I get
```
inputvalues (offered, desired, available) = 100000000, 10000, 0  
amountOffered256 = 0000000000000000000000000000000000000000000000000000000005f5e100  
amountDesired256 = 0000000000000000000000000000000000000000000000000000000000002710  
amountAvailable256 = 0000000000000000000000000000000000000000000000000000000000000000  
amountDesired256 after DivideAndRoundUp = 0000000000000000000000000000000000000000000000000000000000000000
```

OK to merge, and this should probably be considered a critical update.

**Comment by zathras-crypto** [comment]
Just as a heads up - this passed the checkpoint for 420,000 just fine.  

I'm currently syncing the last 1000 or so blocks until it's up to date so I can compare the hashes for the latest block against 0.0.11-rc2 (before we changed this).  I fully expect them to match, it's just another sanity check.

**Comment by dexX7** [comment]
Awesome, thanks for the detailed testing!

**Comment by zathras-crypto** [comment]
0.0.11.1
```
zathras@zathras-pc:~/github/build/omnicore$ src/omnicore-cli omni_getmetadexhash
{
    "block" : 422923,
    "blockhash" : "000000000000000004d5af1014d188d191f81cb68753e2a4c17b5b0b7b7ec03f",
    "propertyid" : 0,
    "metadexhash" : "fe4e32511a4dee94b0670965b86244ddb340cc55e4ff9178c7bf65b59fdf1f47"
}
zathras@zathras-pc:~/github/build/omnicore$ src/omnicore-cli omni_getcurrentconsensushash
{
    "block" : 422923,
    "blockhash" : "000000000000000004d5af1014d188d191f81cb68753e2a4c17b5b0b7b7ec03f",
    "consensushash" : "9f44976c4057510eb0d0431a821afd405b51fc593feea53df3c7ec13f703c63b"
}
```

0.0.11-rc2
```
c:\Program Files\Omni Core\daemon>omnicore-cli.exe omni_getmetadexhash
{
    "block" : 422923,
    "blockhash" : "000000000000000004d5af1014d188d191f81cb68753e2a4c17b5b0b7b7ec03f",
    "propertyid" : 0,
    "metadexhash" : "fe4e32511a4dee94b0670965b86244ddb340cc55e4ff9178c7bf65b59fdf1f47"
}
c:\Program Files\Omni Core\daemon>omnicore-cli.exe omni_getcurrentconsensushash
{
    "block" : 422923,
    "blockhash" : "000000000000000004d5af1014d188d191f81cb68753e2a4c17b5b0b7b7ec03f",
    "consensushash" : "9f44976c4057510eb0d0431a821afd405b51fc593feea53df3c7ec13f703c63b"
}                                            
```

All good on the final test.

I also don't usually use these calls interactively so didn't notice the extra ```propertyid``` field being returned, I'll submit a separate fix for that, so this PR is ready to go.

**Pull request merged**
