### PR TITLE
Use tables and add results to JSON-RPC API documentation

### PR DESCRIPTION
**Pull request by dexX7**
Results were added for all documented API calls.

The text was directly adopted from the help descriptions, and wrapped into code blocks with JavaScript syntax highlighting, for a more appealing presentation.

For consistency, a few help descriptions were shifted.

### CODE REVIEW

**Comment by dexX7** [comment]
I tested a table of content, but this was pretty overwhelming: [see here](https://github.com/dexX7/bitcoin/blob/8948dcff1c87f1bb2887959e3197080ea3ddee6c/src/omnicore/doc/rpc-api.md)

**Comment by dexX7** [comment]
Meh.. I'm split regarding the headlines, capitalization... just let me know what you prefer, and I'm going to change it. :)

**Comment by msgilligan** [comment]
I like the header changes and, of course, having the results documented. I haven't checked for accuracy, but looks good to me.

If you want an automatically-generated table of contents you could use AsciiDoc. :)

**Comment by dexX7** [comment]
Thanks for taking a look, @msgilligan!

What do you think about the highlighting? At first I replaced all keywords like `for`, `this`, `if`, but after uploading the change, I realized that Atom (notepad) highlights different words than GitHub, so I ditched it.

> AsciiDoc

Eventually I'd like to convert everything and generate a HTML documentation, ideally as stunning as chain.com's or dev.blockcypher.com's API docs.

**Comment by msgilligan** [comment]
The highlighting seems fine. 

The things I'd most like to see are:
1. A summary table showing all the calls, their parameters, and a description.
1. The parameter information in table form so it's easier to scan.

I specifically don't like how the parameters look like procedure calls themselves, e.g.:

    endblock (number, optional)

For the Bitcoin RPCs I often find myself going to the bitcoin.it wiki for the [Full List](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list#Full_list) and to the [Developer Reference](https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs) for details on the individual calls. I do **not** like how they created one table for each parameter. I generally like the way JavaDoc produces a method summary with a link to the detailed information, though I'm not crazy about the default JavaDoc style sheets.

I'm working on using Asciidoclet to document the `BitcoinClient` class (and eventually the `OmniClient` class) For each RPC method, I'd like to link back to documentation on the RPC itself.

It would be nice if there were a tool to generate docs for the RPCs themselves, but I'm not sure if there is anything good and JSON-RPC is kind of a special case. It might be worth spending a little time searching for one, though.

**Comment by dexX7** [comment]
Good points!

What I don't like in the developer reference is how they present the results. Larger JSON output with nested elements (see for example ["getrawtransaction"](https://bitcoin.org/en/developer-reference#getrawtransaction)) is a bit aweful.

However, I'm also not really a fan of the way we currently do it. Maybe we should swap "example" and "result", and include an actual result of an example call? On the other hand, this comes with some loss of information: the type and descriptions.

I tested to use tabels. What do you think?

---

### omni_listpendingtransactions

The `"omni_listpendingtransactions"` RPC returns a list of unconfirmed Omni transactions, pending in the memory pool.

Note: the validity of pending transactions is uncertain, and the state of the memory pool may change at any moment. It is recommended to check transactions after confirmation, and pending transactions should be considered as invalid.

**Arguments:**

| Name      | Type   | Presence | Description                                                           |
|-----------|--------|----------|-----------------------------------------------------------------------|
| `address` | string | optional | a filter to include only transactions which involve the given address |

**Result:**

```js
[                                 (array of JSON objects)
  {
    "txid" : "hash",                  (string) the hex-encoded hash of the transaction
    "sendingaddress" : "address",     (string) the Bitcoin address of the sender
    "referenceaddress" : "address",   (string) a Bitcoin address used as reference (if any)
    "ismine" : true|false,            (boolean) whether the transaction involes an address in the wallet
    "fee" : "n.nnnnnnnn",             (string) the transaction fee in bitcoins
    "version" : n,                    (number) the transaction version
    "type_int" : n,                   (number) the transaction type as number
    "type" : "type",                  (string) the transaction type as string
    [...]                             (mixed) other transaction type specific properties
  },
  ...
]
```

**Example:**

```bash
$ omnicore-cli "omni_listpendingtransactions"
```

---

### omni_sendissuancecrowdsale

The `"omni_sendissuancecrowdsale"` RPC can be used to create new tokens as a crowdsale.

**Arguments:**

| Name                | Type   | Presence | Description               |
|---------------------|--------|----------|---------------------------|
| `fromaddress`       | string | required | the address to send from |
| `ecosystem`         | number | required | the ecosystem to create the tokens in (use `1` for main ecosystem, `2` for test ecosystem)  |
| `type`              | number | required | the type of the tokens to create: (use `1` for indivisible tokens, `2` for divisible tokens |
| `previousid`        | number | optional | an identifier of a predecessor token (use `0` for new crowdsales)                           |
| `category`          | string | optional | a category for the new tokens                                                               |
| `subcategory`       | string | optional | a subcategory for the new tokens                                                            |
| `name`              | string | required | the name of the new tokens to create                                                        |
| `url`               | string | optional | an URL for further information about the new tokens                                         |
| `data`              | string | optional | a description for the new tokens                                                            |
| `propertyiddesired` | number | required | the identifier of a token eligible to participate in the crowdsale                          |
| `tokensperunit`     | string | required | the amount of tokens granted per unit invested in the crowdsale                             |
| `deadline`          | number | required | the deadline of the crowdsale as Unix timestamp                                             |
| `earlybonus`        | number | required | an early bird bonus for participants in percent per week                                    |
| `issuerpercentage`  | number | required | a percentage of tokens that will be granted to the issuer                                   |

**Result:**

```js
"hash"   (string) the hex-encoded transaction hash
```

**Example:**

```bash
$ omnicore-cli "omni_sendissuancecrowdsale" "3JYd75REX3HXn1vAU83YuGfmiPXW7BpYXo" 2 1 0 "Companies" "Bitcoin Mining" "Quantum Miner" "" "" 1 "100" 1483228800 30 2
```

---

**Comment by dexX7** [comment]
Alright, I updated a few things. Please let me know, if you like it, or if there is something I should change. For a better comparison, here are the previews:

1. [the original with results](https://github.com/dexX7/bitcoin/blob/ef934545a701cb160fbc01a0f7ff9bbcef2a2e3c/src/omnicore/doc/rpc-api.md)
2. [arguments in tables](https://github.com/dexX7/bitcoin/blob/a3eda895a8778c262656cbdc850870f53780503f/src/omnicore/doc/rpc-api.md)
3. [seperators between each call](https://github.com/dexX7/bitcoin/blob/8a0d97d1038ffa4793087f2beeb26ca7aeae369f/src/omnicore/doc/rpc-api.md)
4. [examples wrapped after 111 characters](https://github.com/dexX7/bitcoin/blob/6daa8d9fec21d48e972216768886cb3121e9f111/src/omnicore/doc/rpc-api.md)
5. [result descriptions without highlighting](https://github.com/dexX7/bitcoin/blob/f424f5c13a64993963c2c46a3c3219bd51e68fda/src/omnicore/doc/rpc-api.md)

I wrapped the example calls after 111 characters to avoid scrollbars. It works on Windows 8.1/Chrome and Ubuntu/Firefox with a resolution of 1920x1080. I'm not sure, if this covers other combinations as well, so let me know, if it's too long.

It would be great, if we could avoid the scrollbars in the results, too, but the tests don't really look nice... see [omni_getactivedexsells](https://github.com/dexX7/bitcoin/blob/07cdf0ad42713fc81c1ed18b4e253c8234227f76/src/omnicore/doc/rpc-api.md#omni_getactivedexsells) and [omni_getcrowdsale](https://github.com/dexX7/bitcoin/blob/07cdf0ad42713fc81c1ed18b4e253c8234227f76/src/omnicore/doc/rpc-api.md#omni_getcrowdsale) as examples.

What do you prefer? Are there other options?

**Comment by msgilligan** [comment]
Preview 4 or 5 look best to me. I think you're pushing the limits of what you can do with markdown and being in the Github page with Github style sheets (and Github column width.)

> Are there other options?

Use a rendering tool (e.g. AsciiDoctor) to create custom, static HTML and publish to Github pages. :+1:

**Comment by dexX7** [comment]
I used (5) with comments in the code blocks.

**Pull request merged**
