### PR TITLE
Do not invalidate MetaDEx cancels if they don't match any open trades

### PR DESCRIPTION
**Pull request by zathras-crypto**
This PR serves to remove the invalidation of MetaDEx cancels if the values provided in the packet are valid but do not result in any matches for open trades to cancel.

### CODE REVIEW

**Comment by dexX7** [comment]
FYI: GitHub seems to have connection failures, and Travis was unable to fetch OmniJ for the regtests.

**Comment by zathras-crypto** [comment]
Ahh, thanks for the heads up :)

**Comment by zathras-crypto** [comment]
Before merging let's just rehash the discussion one more time if that's cool :)

I started making the changes to Send All and I am starting to reconsider my position - I know I've made the case that ```do X with {any}``` shouldn't be invalid if {any} doesn't have any matches, as there is technically nothing invalid about the request - but then I also am starting to think that a Send all with no tokens being valid also doesn't "feel" right - so I'm kind of in split minds now :(

**Comment by dexX7** [comment]
I'm fine with it either way. One may use STO as show case:

- sending non-existing properties is not allowed
- sending zero tokens is not allowed
- transaction is only valid, if there is at least one recipient

From another angle: what would happen on the receiver side, if there were a zero tokens transferred? This could be a bit confusing probably.

**Comment by zathras-crypto** [comment]
> I'm fine with it either way. One may use STO as show case:

Ahh, so we do actually have a precedent here :)  

> *   sending non-existing properties is not allowed

Explicitly set value, value has to be existing property

> *   sending zero tokens is not allowed

Explicitly set value, value has to be in range of allowed values (0 is not in range).

> *   transaction is only valid, if there is at least one recipient

Recipients are not explicitly set values.  This is the interesting bit that only valid if there was at least one recipient :)

The discussion was essentially whether zero matches against what is essentially a wildcard would invalidate the transaction:

* "Send all of {*} to A" (send all)
* "Cancel {*}" (MetaDEx cancel)

Looking at the STO message:

* "Share X of Y between {*}"

We thus already invalidate a transaction in the case of no "matches".  I propose to cancel this PR and continue with the logic that MetaDEx cancels & Send Alls must have at least one "match" to be valid.

**Comment by dexX7** [comment]
> We thus already invalidate a transaction in the case of no "matches". I propose to cancel this PR and continue with the logic that MetaDEx cancels & Send Alls must have at least one "match" to be valid.

Sounds good to me. :)

I'll update the PR and add an OmniJ test for it later.

**Pull request closed without merging**
