### PR TITLE
Introduce global object for consensus parameters

### PR DESCRIPTION
**Pull request by dexX7**
A new base class `CConsensusParams` provides a blueprint for consensus related parameters. The child classes `CMainConsensusParams`, `CTestNetConsensusParams` and `CRegTestConsensusParams` are the actual classes to use, and embed related information for each network.

`ConsensusParams()` is used to access the currently active consensus parameters. The first time this function is called, the parameters are initialized, based on the currently active network.

This allows to finer control over consensus rules for the different networks.

### CODE REVIEW

**Comment by dexX7** [comment]
My plan is to wrap all consensus related parameters into this structure, including activation heights and Exodus addresses for each network, but I'm currently not yet 100 % how to continue from here and how to combine it with the activations.

The most straight forward way would probably be to update the activation heights, as done in #129, but not on a global level, and instead update the values of the parameter objects.

`pCurrentConsensusParams` holds a pointer to the currently active parameters, and is lazy-initialized. `ConsensusParams(const std::string& network)` returns a reference to the parameter objects, which were created as `static` in `rules.cpp`. `ConsensusParams()` (without `std::string`) returns a const reference to the parameters returned by the network-aware sibling.

This seems a bit twisted, but basically mirrors the initialization and handling of the chain params (`chainparams.cpp`, `chainparamsbase.cpp`, ...). The intend is to avoid the creation of the parameter objects over and over again, and simply refer to one, which was created only once.

Instead of having multiple classes, we may just use one class, and populate the values on the fly. This would work fine, given that the child classes only differ in the values of the parameters, and have an identical stucture.

**Comment by dexX7** [comment]
It is thinkable, as first step, to add an activation height for every type, and change the checks as in the following example:

```c++
bool IsAllowedInputType(int whichType, int nBlock)
{
    switch (whichType) {
        case TX_PUBKEYHASH:
            return ConsensusParams().PUBKEYHASH_BLOCK <= nBlock;
        case TX_SCRIPTHASH:
            return ConsensusParams().SCRIPTHASH_BLOCK <= nBlock;
        // ...
    }
    return false;
}
```
I'm mostly wondering about how (ideally all) script and transaction types could be *identified* and bundled. Adding a `FeatureId -> script/transaction type` map and some kind of lookup function might work, but as mentioned, I currently don't see a clear route.

I suggest to continue with the feature activation PR #129 seperately, and mix both step by step.

For review: the commits were created to allow easy commit-by-commit comparisons. I'd consider it as ready at this point, and improvements could be included in subsequent PRs.

**Comment by zathras-crypto** [comment]
This is great stuff mate, I really like the idea - it would be great to move the live blockheights into these classes as you note...

> For review

Reviewed, looks good to me - OK to merge :)

**Comment by dexX7** [comment]
With 269e7ab5107a84887d2a7be9979b95b645f284ec I moved the script related height restrictions into the consensus parameter class, and I removed the params pointer, as well as the lock. This allows switching the network on the fly, at the cost of a string comparison, which may, or may not be cheaper than the removed lock. - It shouldn't have a notable impact.

Converting the transaction restrictions is less straight forward, because we no longer have the plain constants, like `MSC_METADEX_BLOCK`, which can be used at compile time. Rephrased, the following won't work:

```c++
static const int txRestrictionsRules[][3] = {
    {MSC_TYPE_SIMPLE_SEND, ConsensusParams().SEND_BLOCK, MP_TX_PKT_V0},
    {MSC_TYPE_TRADE_OFFER, ConsensusParams().DEX_BLOCK,  MP_TX_PKT_V1},
    // ...
};
```

But instead, we may use something like:
```c++
static const int txRestrictionsRules[][3] = {
    {MSC_TYPE_SIMPLE_SEND, FEATURE_SEND, MP_TX_PKT_V0},
    {MSC_TYPE_TRADE_OFFER, FEATURE_DEX,  MP_TX_PKT_V1},
    // ...
};
```
And then lookup the actual height, based on the feature identifier. Not sure how to structure it yet, though.

**Comment by zathras-crypto** [comment]
Would it be viable to move ```txRestrictionsRules``` into the ```CConsensusParams``` classes and then pass in the type as a parameter to a function within the class?  Something akin to (eg in ```IsTransactionTypeAllowed```)

```
block_FirstAllowed = ConsensusParams().GetLiveBlock(txType);
version_TopAllowed = ConsensusParams().GetMaxVersion(txType);
```

**Comment by dexX7** [comment]
I pushed 996b6b64040e249a3550bed28cd47620cf392d65 as a start, which simplifies `IsTransactionTypeAllowed()` a bit.

> Would it be viable to move txRestrictionsRules into the CConsensusParams ...

Something like that is what I had in mind, too, but I'm not exactly sure how. It would probably make sense to get rid of `txRestrictionsRules` (now: `vTxRestrictions`) altogether, on a global scope, and have the information directly in the params classes.

How would you do the lookup/data retrieval in the class?

At the moment my plan was to add a map to the param classes with "feature identifier" as key, and "activation height" as value, and then replace the check in `IsTransactionTypeAllowed()` to something like:
```c++
if (txBlock >= ConsensusParams().GetActivationBlock(entry.featureId)) {
    return true;
}
```

**Comment by dexX7** [comment]
Alright, I moved the restrictions into the consensus params class. It feels a bit like a [workaround](https://github.com/dexX7/bitcoin/blob/d267d104160b5585ee79a68a9f03fa5271b31cea/src/omnicore/rules.cpp#L27) though,

The [activation heights](https://github.com/dexX7/bitcoin/blob/d267d104160b5585ee79a68a9f03fa5271b31cea/src/omnicore/rules.h#L38-L71) of the params classes are mutable, and it's possible to update values.

Right now however, there are two ways to access the params:

- `ConsensusParams()` returns a const reference (immutable)
- `ConsensusParams(const std::string& network)` returns a reference (mutable)

I added a test to [update the height](https://github.com/dexX7/bitcoin/blob/d267d104160b5585ee79a68a9f03fa5271b31cea/src/omnicore/test/params_tests.cpp#L35-L55) of the bet transaction activation, which may serve as blueprint.

Depending on where we go from here, I suggest we either use the function to get the mutable params object, where the network is supplied, or we add another function such as:
```c++
CConsensusParams& MutableConsensusParams()
{
    const std::string& network = Params().NetworkIDString();
    return ConsensusParams(network);
}
```

This would probably be more expressive/intuitive. Please let me know, if there is anything you'd do differently. :)

Regarding the review process: since the last one, the following commits were added:

- 269e7ab5107a84887d2a7be9979b95b645f284ec Replace script related block heights with consensus params
- 996b6b64040e249a3550bed28cd47620cf392d65 Restructure handling of transaction activation heights
- d267d104160b5585ee79a68a9f03fa5271b31cea Move transaction restrictions into ConsensusParams()

**Comment by dexX7** [comment]
Rebased and updated.

The checkpoints are now part of the consensus parameters.

Since the initial review:

- 2531ddf5241401bcc6eda915797289b324d98c83 Replace script related block heights with consensus params
- 053abbaed8a391b545f36fe7a64c638765ccb225 Restructure handling of transaction activation heights
- 2098d267b0b1305bc5ba6395e8a0a34d6f5b5479 Move transaction restrictions into ConsensusParams()
- ad9e9add26911111cd00e5020c3ac43e589b0b1a Test and refine documentation of consensus hashing
- 964e34c68f15b3e4945d32821bd26e44f4cea66f Move consensus checkpoints into consensus params classes

**Comment by zathras-crypto** [comment]
Awesome thanks dude, just landed and shattered but will take a proper look
tomorrow and refocus on the feature activation stuff.

As always huge thanks for your work :)
Z

**Comment by dexX7** [comment]
Alright, I added:

- 34e745a1e535274f6647ffdfba0bcb159fa33387 Support mutable access of consensus parameters

This is what I outlined in https://github.com/OmniLayer/omnicore/pull/144#issuecomment-124919693.

[The test](https://github.com/OmniLayer/omnicore/blob/34e745a1e535274f6647ffdfba0bcb159fa33387/src/omnicore/test/params_tests.cpp#L59-L73) demonstrates how to update parameters. I think you can go on from here rather easily, and simply replace all `XXX_BLOCK` with `MutableConsensusParams().XXX_BLOCK`.

**Comment by dexX7** [comment]
@zathras-crypto: OK to merge?

**Comment by zathras-crypto** [comment]
> OK to merge?

Indeed :)  OK with me mate...

Completely off-topic, I just used your faucet & it's pretty cool!!!  I'm trying to replicate @CraigSellars issue in https://github.com/OmniLayer/omnicore/issues/154 and not having much luck on testnet, but then realized he's on mainnet test ecosystem - since I don't have access to my mainnet testing wallet remotely I needed some TMSC to play with & your faucet did the job nicely hehe :)

**Comment by dexX7** [comment]
As mentioned in another commit comment, I added:

- 7d86bfeb08610679fb65bdcb25ddbc0262171e12 Don't bypass transaction restrictions on non-mainnet networks

I'm going to wait until Travis finishes, and then I'll merge.

> Completely off-topic, I just used your faucet & it's pretty cool!

Haha, thanks! Ping me, if you need some more TMSC. :)

**Comment by zathras-crypto** [comment]
> I'm going to wait until Travis finishes, and then I'll merge.

Sounds good :)

Speaking of Travis, my feature activation branch fails, I understand this one because I changed the value to test activations for MetaDEx on testnet:

```
omnicore/test/params_tests.cpp(32): error in "network_restrictions_test": check params.MSC_METADEX_BLOCK == 0 failed [999999 != 0]
```

But this one I'm not sure about, I didn't change anything related to simple send (or so I thought)
```
omnicore/test/rules_txs_tests.cpp(31): error in "simple_send_restrictions": check IsTransactionTypeAllowed(0, 2, MSC_TYPE_SIMPLE_SEND, 0) failed
```

Any thoughts?

> Haha, thanks! Ping me, if you need some more TMSC. :)

Hehe, already did, Craig's trade is indivisible so requires a whole TMSC :)

**Comment by dexX7** [comment]
> Speaking of Travis, my feature activation branch fails, I understand this one because I changed the value to test activations for MetaDEx on testnet

Could you point me to the commit, where you changed the activations?

I sort of assumed this will happen at some point, if I use hardcoded values for the tests.

The `params_tests.cpp` test fails due to the [following lines](https://github.com/dexX7/bitcoin/blob/oc-0.10-consensus-params/src/omnicore/test/params_tests.cpp#L28-L33):
```c++
BOOST_AUTO_TEST_CASE(network_restrictions_test)
{
    const CConsensusParams& params = ConsensusParams("test");
    BOOST_CHECK_EQUAL(params.MSC_STO_BLOCK, 0);
    BOOST_CHECK_EQUAL(params.MSC_METADEX_BLOCK, 0);
}
```

If you changed the activation block for the MetaDEx on testnet, then the last line won't pass. In this case I suggest to replace the 0. I wanted to show with the test that the correct height is retrieved from the params, and that the height is a different one than the one used on mainnet.

And the [other one](https://github.com/dexX7/bitcoin/blob/oc-0.10-consensus-params/src/omnicore/test/rules_txs_tests.cpp#L31):
```c++
BOOST_CHECK(IsTransactionTypeAllowed(0, OMNI_PROPERTY_TMSC, MSC_TYPE_SIMPLE_SEND, MP_TX_PKT_V0));
```
... which is a bit strange actually.

**Comment by zathras-crypto** [comment]
> Could you point me to the commit, where you changed the activations?

Sure, https://github.com/zathras-crypto/omnicore/commit/64cac92546deab4bd820a00c2e8986c4cbd71ffd changed ```MSC_METADEX_BLOCK``` to 999999 in the testnet consensus params, and I understand why that fails the ```BOOST_CHECK_EQUAL(params.MSC_METADEX_BLOCK, 0);``` test (simple enough to change).  

What threw me was the simple send failure, because I hadn't changed anything related to that and from what I can tell of the code, it should happily pass.

> And the other one: ... which is a bit strange actually.

Heh, that about sums it up !!  I'm struggling to see why this fails.

**Pull request merged**
