### PR TITLE
Change icon to make Win64 installer deterministic

### LINKED ISSUE #230: Win64 installer via Gitian is not deterministic
Since the second developer preview, as it looks like, we were unable to produce a deterministic Win64 installer. The cause is still unknown.

So far I've tested Debian 7.8, Debian 8.1, a Windows 8.1 host, a Windows 10 host, and using a Debian 8.1 instance via EC2.

As next step I'm going to build the tip of bitcoin:0.10 (https://github.com/bitcoin/bitcoin/commit/ae52a7ffd1b3743e76220812c7f581c5c08f975b), to see, whether this produces similar results. I'm also going to test to build the 0.10 tag, for which a bunch of [results](https://github.com/bitcoin/gitian.sigs/tree/master/0.10.0-win) are available upstream, if the tip is not deterministic.

This is a rather crude approach to pin down the issue, but I'm out of ideas. If the 0.10 tip is deterministic, then I'm going to replace our [omnicore-0.0.10/src/omnicore/res/omnicore-setup-win.nsi.in](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/omnicore/res/omnicore-setup-win.nsi.in) with the original [share/setup.nsi.in](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/share/setup.nsi.in).

The alternative I can currently think of is to manually go through all steps, i.e. mirror the behavior of Gitian.

### PR DESCRIPTION
**Pull request by dexX7**
This pull request restore the original image sizes of the program icon to make the Win64 installer deterministic.

On the left is the old icon, on the right the updated icon:

icons

This seems to resolve #230.

### CODE REVIEW

**Comment by zathras-crypto** [comment]
In the comparison image, the icon sizes and bit depths seem to be the same - purely just for interest what was the problem?

Thanks so much for getting to the bottom of the build mismatch :)

**Comment by dexX7** [comment]
To be honest, I'm not sure actually. But just to clarify: the image on the left was the one used for preview 1, which was deterministic, the image on the right is the image of this PR, which exactly mirrors the sizes of the determinitic image.

For preview 2+, which were not deterministic, we used the following icons (right side for Windows):



So all I did here was basically to remove the extra images, with other resolutions, such as 768x768.

It's not clear to me why extra images are an issue. If it were the other way around, I might understand (because then an image with resolution, which isn't available, might be constructed on the fly or so).

**Comment by zathras-crypto** [comment]
> So all I did here was basically to remove the extra images, with other resolutions, such as 768x768.

Ahh I see, thanks.

> It's not clear to me why extra images are an issue. If it were the other way around, I might understand (because then an image with resolution, which isn't available, might be constructed on the fly or so).

That would be my thinking too, perhaps the higher resolution images trigger some other sampling or something - but glad you got it sorted :)

**Comment by dexX7** [comment]
> but glad you got it sorted

Me, too! But let's hope it's really resolved. The tests shown above also revealed that the 32 bit installers are not always matching, even though you and me got the same results for win32 installers of preview 2.

**Pull request merged**
