### PR TITLE
Implement tally hashing for consensus testing and checkpoints

### PR DESCRIPTION
**Pull request by zathras-crypto**
Consensus testing currently relies on looping through every property and checking the balance for every address.  This PR serves to distill that process down into a single hash, which can be used for consensus testing but also be used as a form of checkpointing (by verifying that all balances for all properties are as expected at a given block).  

This PR also implements a checkpointing system, and hardcoded checkpoints for every 10,000 blocks.  Strictly speaking only the most recent checkpoint is needed and earlier checkpoints may be removed later, however in the early stages of this PR and while it's being tested it is useful to have earlier checkpoints listed as this allows checkpoint verification functions to be tested earlier in the parsing process.

The RPC call ```omni_getcurrentconsensushash``` may be used to obtain the hash for the current block.

Feedback would be most welcomed :)

### CODE REVIEW

**Comment by dexX7** [comment]
Wow..

This is awesome, very clean and great to step through! I really like it!

My two main points:

1. I suggest to associate consensus hashes with block hashes, instead of block heights. Or ideally with block hashes, heights and consensus hashes, to avoid any ambiguousness. In this case we'd even be able to handle 10k deep reorgs (yes, yes.. not going to happen, but still).

2. While we don't store empty balance entries, we may very well have some at runtime, because we don't explicitly clean up the tally map (or the balance records of a tally entry). Please correct me, if I'm wrong though. A check, whether an entry/record is empty could be added, and then we should be good.

And a tricky question:

- Let's assume some user [or we] detect a consensus difference. What would you say/respond to that user, and which steps would you take next?

**Comment by zathras-crypto** [comment]
> This is awesome, very clean and great to step through! I really like it!

Thanks dude!!! :)

> I suggest to associate consensus hashes with block hashes, instead of block heights. Or ideally with block hashes, heights and consensus hashes, to avoid any ambiguousness. 

OK, sure - that's probably the smart move - leave it with me...

> While we don't store empty balance entries, we may very well have some at runtime, because we don't explicitly clean up the tally map (or the balance records of a tally entry). 

Fantastic - great feedback!  I'd only tested by spoofing failures during initial parsing - you're completely right empty balances could skew the results during runtime - I'll filter out empty balances from the process.

> Let's assume some user [or we] detect a consensus difference. What would you say/respond to that user, and which steps would you take next?

I had intended that if a checkpoint failed to match then the code should not be allowed to continue because the data could not be trusted.  Agree we should inform the user, perhaps with a message that the state is not as expected and thus the data is not to be trusted followed by a node shutdown.  

Otherwise when using the hash for simplified consensus testing I would imagine that we would do similar to current in the event we introduce a difference (ie track down what had caused the difference and revert/address it).

> It could be handy to have an "ultra debug/diagnostic mode", directly in GetConsensusHash(), where, if active, the line to hash is printed as well.

Sure, straight forward enough, will add that in.

> ...various commit comments...

Nice, thanks - these are good points, I'll update to address them...

Thanks again dude, really helpful feedback :)

**Comment by dexX7** [comment]
> OK, sure - that's probably the smart move - leave it with me...

Since you used `std::pair`, something like the following should be possible:
```c++
struct ConsensusCheckpoint
{
	int blockHeight;
    uint256 blockHash;
    uint256 consensusHash;
};

// ...

static const ConsensusCheckpoint vCheckpoints[] =
{
	{ 250000, uint256("00...11"), uint256("12...23") },
	{ 260000, uint256("00...11"), uint256("12...23") },
	// ..
};
```

... or maybe a `std::map` with height as key, and a `std::pair` as value. You'll figure something out, I'm sure.. :)

**Comment by zathras-crypto** [comment]
> I suggtest to merge #145 (once empty entries are skipped)

Implicit ACK, merging - please shout if I'm overstepping by doing this :)

**Comment by dexX7** [comment]
> Implicit ACK, merging - please shout if I'm overstepping by doing this :)

It's fine, but I'm a bit worried about the notes in #135 though. Could you quickly clarify, whether the checkpoints are faulty?

**Comment by zathras-crypto** [comment]
Sure, sorry for any confusion.

Long story short changing the hashing scheme to ignore empty balances
invalidated the original checkpoints.  There is now a new set of
checkpoints that is valid for the modified GetConsensusHash() code.

The confusion came about as I didn't pick this up until testing the seed
block stuff, but it's unrelated - it was just what highlighted the issue
for me.

Does that clear it up?

**Comment by dexX7** [comment]
Ah, I see, I see. Thanks.

It looks like the following build failed due to a hash mismatch, and now stalls:

https://ci.omni.foundation/job/omni-mainnet-consensus/97/console

If you have CI server access, please cancel and restart. Was this after the update of the hashes?

**Comment by zathras-crypto** [comment]
> If you have CI server access, please cancel and restart. 

Sadly I'm not sure of my credentials - Sean did give me access but I haven't used it in so long I can't recall my login details - sorry :(

Paging @msgilligan

**Comment by dexX7** [comment]
I created https://github.com/OmniLayer/OmniJ/issues/91.

Do you know, if this is the build with the old or New checkpoint list?

**Comment by zathras-crypto** [comment]
If you check here https://ci.omni.foundation/job/omnicore-integration/43/ you should see that https://github.com/OmniLayer/omnicore/commit/a0cbeb429a52c238c9b61ecd7ebffc9e880029f3 is the last commit in that build, and it wasn't until a few commits later in https://github.com/OmniLayer/omnicore/commit/a721e631cb274a01e8053a04a5ba33ec6ff2e581 that the new checkpoints were introduced.  

So I'd strongly suspect this is a build with the old checkpoint list, though I'm not familiar enough with CI to say 100%.

**Comment by dexX7** [comment]
Ah, now I see. Thanks!

I'm going to rebase #144 later, and when I find some time, I'll try to add a few unit tests for the tally hasing.

**Comment by dexX7** [comment]
I cleared all Omni related files, and started the parsing from scratch on a $ 80 DigitalOcean droplet.

It was successful. :) Therefore I can confirm the new checkpoints are indeed correct.

As a sidenote: the parsing took 35 minutes (no block skipping, based on omnicore-0.0.10 tip + address index).

**Pull request merged**
