### PR TITLE
Port code base to Bitcoin Core 0.13.2

### PR DESCRIPTION
**Pull request by dexX7**
This pull request merges/ports Bitcoin Core 0.13.2 into our code base.

There were two minor conflicts due to the renaming of "Bitcoin Core" to "Omni Core", otherwise the merge was clean.

See https://github.com/bitcoin/bitcoin/blob/v0.13.2/doc/release-notes.md for the release notes.

### CODE REVIEW

**Comment by dexX7** [comment]
This still needs some tweaks, e.g. here:

https://travis-ci.org/OmniLayer/omnicore/jobs/190282352#L1494

**Comment by dexX7** [comment]
I fixed one remaining issue via 162429ebf5522f71069027ee0a91bb20a15494f5, but there is still an issue with the RPC tests, and right now I can't figure out what's causing it. When I run the whole test suite, at some point [it crashes](https://travis-ci.org/OmniLayer/omnicore/jobs/190282348#L6928), but when running these tests isolated, they all pass..

I'm waiting for some feedback from @msgilligan.

**Comment by dexX7** [comment]
Last issue resolved via 8d8d0bfdea7b6c7b3baca10d67c592a4e63f3dba.

Ready for review. @zathras-crypto :)

**Comment by zathras-crypto** [comment]
Awesome thanks for prepping this @dexX7...

I'm testing now - given these are all commits to the underlying Bitcoin source I wouldn't need to test each individual commit I believe?

Thanks
Z

**Comment by dexX7** [comment]
Yup, they are directly taken from the 0.13 Bitcoin Core branch. :)

**Comment by zathras-crypto** [comment]
Been testing this out for a few days, haven't noticed anything unusual, looks good - OK to merge :)

Thanks bud :)

**Pull request merged**
