### PR TITLE
[Meta DEx] enable RPC calls, add missing "cancel" logic

### PR DESCRIPTION
**Pull request by dexX7**
Part I)

The meta DEx RPC calls are currently completely "removed" via preprocessor makros, however, this is only user faced, and does not affect how meta DEx transactions are parsed, so there should basically be no difference. Using the category `"hidden"` further hides the calls from `help`, but they can be used nevertheless. This seems handy for testnet or regtests.

Part II)

This implements the missing logic of "cancel" operations on the meta DEx.

To quote the [spec](https://github.com/mastercoin-MSC/spec#sell-master-protocol-coins-for-another-master-protocol-currency), in particular for action = 4:

> An offer to sell coins can be changed or cancelled by publishing additional transactions with [metadex sell offer sub-action](https://github.com/mastercoin-MSC/spec#field-metadex-sell-offer-sub-action) variations:

> - [Action](https://github.com/mastercoin-MSC/spec#field-metadex-sell-offer-sub-action) = 1 (ADD) orders are merged (both in the database and the UI) when their unit prices are exactly the same.

> - [Action](https://github.com/mastercoin-MSC/spec#field-metadex-sell-offer-sub-action) = 2 (CANCEL-AT-PRICE) cancells open orders for a given set of currencies at a given price. It is required that the [currency identifiers](https://github.com/mastercoin-MSC/spec#field-currency-identifier) and price exactly match the order to be canceled.

> - [Action](https://github.com/mastercoin-MSC/spec#field-metadex-sell-offer-sub-action) = 3 (CANCEL-ALL-FOR-CURRENCY-PAIR) cancels all open orders for a given set of two currencies (one side of the order book).

> - [Action](https://github.com/mastercoin-MSC/spec#field-metadex-sell-offer-sub-action) = 4 (CANCEL-EVERYTHING) can be used to cancel all open orders for all currencies within one ecosystem, if [currency identifier for sale](https://github.com/mastercoin-MSC/spec#field-currency-identifier) and [currency identifier desired](https://github.com/mastercoin-MSC/spec#field-currency-identifier) are within the same ecosystem, otherwise all open orders for all currencies of both ecosystems are cancelled.

> When using [action](https://github.com/mastercoin-MSC/spec#field-metadex-sell-offer-sub-action) = 3 (CANCEL-ALL-FOR-CURRENCY-PAIR) the validity of the following fields is not tested:

> - Amount for sale
> - Amount desired

> When using [action](https://github.com/mastercoin-MSC/spec#field-metadex-sell-offer-sub-action) = 4 (CANCEL-EVERYTHING) the validity of the following fields is not tested:

> - Currency identifier for sale
> - Amount for sale
> - Currency identifier desired
> - Amount desired

### CODE REVIEW

**Comment by m21** [comment]
Guys check out my old branch for 10:https://github.com/mastercoin-MSC/mastercore/commit/61f808a11011c6ecd40dba8eddb004220407364c
I simply reenabled Metadex , but more importantly renamed all the binaries to "omnicore" in previous commits.

**Comment by dexX7** [comment]
Let's give this a few more days, but at least one "it's good to go" would be great.

As next step, I'd split `mastercore_dex` into `mastercore_dex` and  `mastercore_mdex`, because both have basically nothing in common, and come with a very different logic.

**Comment by zathras-crypto** [comment]
I checked this out when you first put it out mate, "it's good to go" WRT the RPC stuff.  The cancel stuff though I can't comment on until I dive into MetaDEx math/logic, which I've been purposely avoiding while I catch up on the rest of my work queue.

> This implements the missing logic of "cancel" operations on the meta DEx.

I wondered about this part - so @m21's implementation as it stands has *no* cancel operations or *broken* cancel operations?

**Comment by dexX7** [comment]
Alright, in this case it might make sense to split the PR, since it seems there might be need for further discussion.

The more obvious part: the checks for `CANCEL_AT_PRICE` and `CANCEL_ALL_FOR_PAIR` are indeed missing and tagged as `TODO`. The PR just fills the blanks here.

The missing *logic* of `CANCEL_EVERYTHING` goes a long way back from https://github.com/mastercoin-MSC/mastercore/issues/219 to https://github.com/mastercoin-MSC/spec/pull/292. Initially, this command canelled all offers of *both* ecosystems in any case, and it's behavior was changed to:

> Action = 4 (CANCEL-EVERYTHING) can be used to cancel all open orders for all currencies within one ecosystem, if currency identifier for sale and currency identifier desired are within the same ecosystem, otherwise all open orders for all currencies of both ecosystems are cancelled.

This was something undefined, spec wise, at that point, and neither covered by the test plan.

**Comment by dexX7** [comment]
The last commit is a fix for minimal faulty code as well as a undefined variable and a straight forward optimization of the initialization of those variables.

I'm going to start testing of the merged version now, and if there is flawless, which I expect, given the intensive testing some weeks ago, as well as when I submitted this PR, this is good to go.

For once, because any further work on the meta DEx is dependant on this PR, and it further looks like @zathras-crypto is already integrating the meta DEx UI into #5.

Regarding the logic: this was specified more than a few weeks ago, and this PR merley catches up with the spec. If, for some reason, the spec gets changed again, it can be addressed by a follow up PR.

**Comment by dexX7** [comment]
Travis CI build result: **passed**
https://travis-ci.org/dexX7/bitcoin/builds/57771300 

RPC tests via bitcoin-spock: **passed**
http://bitwatch.co/uploads/omnicore-pr-8/

RPC tests via [mastercore-rpc-tests](https://github.com/dexX7/mastercore-rpc-tests), including meta DEx test plan: **passed**
http://bitwatch.co/uploads/omnicore-pr-8/run_future_tests.log

```
Test summary:

ExodusPurchaseTest ... successful
SimpleSendTest ... successful
PropertyCreationTest ... successful
P2SHTest ... successful
TraditionalDexTest ... successful
SendToOwnersTest ... successful
MetaDexPlanTest ... successful
MetaDexCancelAtPriceTest ... successful
MetaDexCancelPairAndLookupTest ... successful
DexCrossEcosystemSideEffectsTest ... successful
MetaDexCancelEverythingInSameEcosystemTest ... successful
MetaDexCancelEverythingIgnorePropertyTest ... successful
MetaDexCancelEverythingScopeTest ... successful

13 of 13 tests successful (0 skipped)
```

**Pull request merged**
