### PR TITLE
Run OmniJ tests with all build targets except OS X

### PR DESCRIPTION
**Pull request by dexX7**
The Windows binaries are "routed" through wine, which works surprisingly well with a few minor adjustments.

The build/test time may be longer though.

### CODE REVIEW

**Comment by zathras-crypto** [comment]
> Storing extra information about a crowdsale, when closing one, provides no gain, given that this information can also be retrieved via RPC.

I'm not against removing it per se (though ideally it'd be nice to know *why* it crashes 32-bit builds) but perhaps it might be better to shift it into ```msc_debug_sp``` or a new ```msc_debug_crowdsale``` flag rather than getting rid of it completely (in the case that we want to verify log vs RPC data)

**Comment by dexX7** [comment]
Ah, please note that I added the crowdsale commit to this PR only temporary, to test Travis. :)

Travis is really awesome, and I think we should always run the tests, if possible, but unfortunally this has a negative impact on the test time with about 3-12 minutes more per build target.

So far it looks like, assuming there are no other builds in the queue, the total time is around 16-20 minutes. I guess that's not horrible, and ideally builds are tested locally anyway, but it still makes a difference.

What do you think?

**Comment by zathras-crypto** [comment]
> What do you think?

I would always sacrifice build time for more testing.   In a heartbeat.

**Comment by dexX7** [comment]
Well then, let's figure out how to deal with the crowdsale dumping issue and get it in then. :)

**Pull request merged**
