### PR TITLE
Add functions for more expressive RPC input validation

### PR DESCRIPTION
**Pull request by dexX7**
The idea is to have `ParseXYZ()` functions to convert user input, while respecting value ranges and other type requirements, which are universal and not state dependent (e.g. `ecosystem = 5` is always wrong), as well as `RequireCondition()` functions to check specific requirements, depending on the user action and state (e.g. `"there must be no other active DEx offering"`). If something is unexpected, then `JSONRPCError` are thrown.

Right now there are the following parsing functions:

 - `ParseAddress(const json_spirit::Value& value)`
 - `ParsePropertyId(const json_spirit::Value& value)`
 - `ParseAmount(const json_spirit::Value& value, bool isDivisible)`
 - `ParseAmount(const json_spirit::Value& value, int propertyType)`
 - `ParseDExPaymentWindow(const json_spirit::Value& value)`
 - `ParseDExFee(const json_spirit::Value& value)`
 - `ParseDExAction(const json_spirit::Value& value)`
 - `ParseEcosystem(const json_spirit::Value& value)`
 - `ParsePropertyType(const json_spirit::Value& value)`
 - `ParsePreviousPropertyId(const json_spirit::Value& value)`
 - `ParseText(const json_spirit::Value& value)`
 - `ParseDeadline(const json_spirit::Value& value)`
 - `ParseEarlyBirdBonus(const json_spirit::Value& value)`
 - `ParseIssuerBonus(const json_spirit::Value& value)`
 - `ParseMetaDExAction(const json_spirit::Value& value)`

And the following requirement checks:

 - `RequireEnoughBalance(const std::string address, uint32_t propertyId, int64_t amount)`
 - `RequireOnlyMSC(uint32_t propertyId)`
 - `RequireNonEmptyPropertyName(const std::string& name)`
 - `RequireExistingProperty(uint32_t propertyId)`
 - `RequireCrowdsale(uint32_t propertyId)`
 - `RequireActiveCrowdsale(uint32_t propertyId)`
 - `RequireManagedProperty(uint32_t propertyId)`
 - `RequireTokenIssuer(const std::string& address, uint32_t propertyId)`
 - `RequireMatchingDExOffer(const std::string& address, uint32_t propertyId)`
 - `RequireNoOtherDExOffer(const std::string& address, uint32_t propertyId)`
 - `RequireSaneReferenceAmount(int64_t amount)`
 - `RequireSaneDExPaymentWindow(const std::string& address, uint32_t propertyId)`
 - `RequireSaneDExFee(const std::string& address, uint32_t propertyId)`
 - `RequireHeightInChain(int blockHeight)`

It might appear to be an overkill, if there are many very specific checks, but I think it would be neat, if one could take a look at a few lines of code, and immediately get a very clear understanding of what's going on.

The error messages were adopted from the existing error messages, but ultimately I'd like to refine them, and also include the user input in the error message.

It does not update the RPC calls yet, because I'd like to discuss the names, and checks first. Do the names make sense? What might be added?

### CODE REVIEW

**Comment by zathras-crypto** [comment]
I really like the direction here - think it will really help improve code readability and understanding of flow -  have to pop out now but when I get back I'll run over the names and provide some feedback :)

**Comment by zathras-crypto** [comment]
> I'd like to discuss the names

* I tend to prefer DEx over Dex ("Distributed Exchange" rather than "Distributed exchange") - also maintains consistency with current code
* "commitment fee" I'm not sure about terminology there - I haven't seen that used elsewhere (usually some derivation of min fee or min accept fee)
* "PaymentTimeframe" could perhaps be "PaymentWindow" (matches spec)
* Any reason to introduce a different term for issuer (administrator)?
* ```RequireHeightInRange``` could be perhaps more descriptive as ```RequireHeightInChain```?

Don't take any of that feedback as gospel, just thinking out loud as I went over the names - naming conventions always end up as a subjective discussion (what seems right to one person may not seem right to another, but it doesn't mean either party is right or wrong) :)

> and checks first ... What might be added?

To be honest my methodology for this would likely be to step through each of the existing RPC calls and abstract those existing checks into these new standalone functions - though I kind of suspect you've already done that :)

**Comment by dexX7** [comment]
Thanks, this is exactly what I was looking for! :)

> Any reason to introduce a different term for issuer (administrator)?

Issuer would be in line with the rest, as well as the wording in the spec, and maybe my understanding of "issuer" isn't accurate, but at least for me "issuer" sounds like "the one who created a property", which is a one time event. Alternatively, maybe "manager", or is "issuer" actually fine?

**Comment by zathras-crypto** [comment]
> Issuer would be in line with the rest, as well as the wording in the spec, and maybe my understanding of "issuer" isn't accurate, but at least for me "issuer" sounds like "the one who created a property", which is a one time event. Alternatively, maybe "manager", or is "issuer" actually fine?

Ahh I see... There is this current concept of the issuer *on record* - the "issuer on record" isn't necessarily the same as the issuer of the property (because it can be changed via the change issuer transaction).  So when I think of "issuer" I kind of automatically think "issuer in the SP object" rather than "address that sent the initial creation transaction" but that might just be me - have a quick skim of https://github.com/mastercoin-MSC/spec#change-issuer-on-record-for-a-smart-property and see what you think - we always have the option of having two distinguished attributes (issuer = address that sent creation transaction & administrator = address that has current control of the property).

**Comment by dexX7** [comment]
Very good points. I'll stick to `RequireTokenIssuer` then. :)

I agree with the rest, and will update shortly. How about those:

- RequireEnoughBalance (enough or sufficient?)
- RequireOnlyMSC (it's unclear what is meant here: only MSC and TMSC are allowed)
- RequireNonEmptyPropertyName (this one might a bit long)

**Comment by zathras-crypto** [comment]
> RequireEnoughBalance (enough or sufficient?)

Honestly, I don't think you need either - ```RequireBalance``` gets the point across - you could go ```RequireAvailableBalance``` I guess also - but ```RequireBalance``` is succinct enough imo :)

> RequireOnlyMSC (it's unclear what is meant here: only MSC and TMSC are allowed)

It was clear to me - but then I'm obviously code-familiar and part of the point of this is to make things easier to follow so agree could be more descriptive - also thinking about it some more given the pending rebrand of Mastercoins to Omnis / Omni tokens / Omni coins whatever that ends up being, perhaps putting token abbreviations like MSC directly in function names should be avoided?  Perhaps some form of naming prefixed with ```RequireValid``` eg ```RequireValidDExToken``` or something similar?

> RequireNonEmptyPropertyName (this one might a bit long)

Probably don't need "NonEmpty" - ```RequirePropertyName``` already implies a name is required...  Again could use the 'valid' moniker and go ```RequireValidPropertyName``` but not sure if it's needed...

**Comment by dexX7** [comment]
> RequireBalance
> RequirePropertyName

Hehe, simplicity is key. I like it! :)

> RequireValidXXX

We never allow invalid input, so it doesn't feel right. Maybe `RequireBaseTokens()`? Though that is probably also cryptic, if it's unknown what we refer to.

**Comment by zathras-crypto** [comment]
> Maybe RequireBaseTokens()? Though that is probably also cryptic, if it's unknown what we refer to.

Heh - I also use a similar concept referring to MSC/TMSC as "primary" tokens (you'll probably see that somewhere in my UI metadex code no doubt) but I haven't done that user-facing because I had the same worry (people might not know what I was talking about!)

**Comment by dexX7** [comment]
Ah, "primary" sounds great. Not *very* descriptive, but much better than my previous ideas.

**Comment by dexX7** [comment]
Right now I have the following error messages for requirements:

 - "Sender has insufficient balance"
 - "Sender has insufficient balance (due to pending transactions)"
 - "Property identifier must be 1 (MSC) or 2 (TMSC)"
 - "Property name must not be empty"
 - "Property identifier does not exist"
 - "Property identifier does not refer to a crowdsale"
 - "Property identifier does not refer to an active crowdsale"
 - "Property identifier does not refer to a managed property"
 - "Sender is not authorized to manage the property"
 - "No matching sell offer on the distributed exchange"
 - "Another active sell offer from the given address already exists on the distributed exchange"
 - "Reference amount is heigher than 0.01 BTC"
 - "Payment window is less than 10 blocks (use overwrite = true to continue)"
 - "Minimum accept fee is higher than 0.01 BTC (use overwrite = true to continue)"
 - "Block height is out of range"
 
Criticism welcomed. ;)

**Comment by zathras-crypto** [comment]
Minor nits 

> "Reference amount is heigher than 0.01 BTC"

higher

> "Payment window is less than 10 blocks (use overwrite = true to continue)"
> "Minimum accept fee is higher than 0.01 BTC (use overwrite = true to continue)"

override

**Comment by dexX7** [comment]
Thanks.

The value errors:

 - "Invalid address"
 - "Invalid property identifier"
 - "Amount must be positive"
 - "Payment window must be within 1-255 blocks"
 - "Mininmum accept fee must be positive"
 - "Invalid action (1 = new, 2 = update, 3 = cancel only)"
 - "Invalid ecosystem (1 = main, 2 = test only)"
 - "Invalid property type (1 = indivisible, 2 = divisible only)"
 - "Property appends/replaces are not yet supported"
 - "Text must not be longer than 255 characters"
 - "Deadline must be positive"
 - "Early bird bonus must be in the range of 0-255 percent per week"
 - "Bonus for issuer be in the range of 0-255 percent"

**Comment by zathras-crypto** [comment]
> "Bonus for issuer be in the range of 0-255 percent"
must

**Comment by zathras-crypto** [comment]
Looking good dude :)

**Comment by dexX7** [comment]
Hehe, time to get a coffee.. :) Thanks!

Does this affect any ongoing work, or would you consider it as ready? `rpc.cpp` isn't touched at the moment.

**Comment by zathras-crypto** [comment]
> Does this affect any ongoing work

Not for me, I'm pottering around in ```rpc.cpp``` but haven't touched ```rpctx.cpp``` for a while :)

**Comment by daidai2016** [comment]
> Right now I have the following error messages for requirements:
> 
> * "Sender has insufficient balance"
> * "Sender has insufficient balance (due to pending transactions)"
> * "Property identifier must be 1 (MSC) or 2 (TMSC)"
> * "Property name must not be empty"
> * "Property identifier does not exist"
> * "Property identifier does not refer to a crowdsale"
> * "Property identifier does not refer to an active crowdsale"
> * "Property identifier does not refer to a managed property"
> * "Sender is not authorized to manage the property"
> * "No matching sell offer on the distributed exchange"
> * "Another active sell offer from the given address already exists on the distributed exchange"
> * "Reference amount is heigher than 0.01 BTC"
> * "Payment window is less than 10 blocks (use overwrite = true to continue)"
> * "Minimum accept fee is higher than 0.01 BTC (use overwrite = true to continue)"
> * "Block height is out of range"
> 
> Criticism welcomed. ;)

Property identifier does not refer to a managed property，

How to solve this problem？

**Pull request merged**
