### PR TITLE
Reduce scope of LOCKs

### LINKED ISSUE #85: Hold LOCKs only as long as necessary
As outlined in #84,`gettransactions_MP` and other parts currently lock certain sections longer than necessary.

In case of `gettransactions_MP` an additional improvement could be to restructure the command, such that we lock the wallet, collect the wallet transactions, release the lock, and then process the transactions, instead of holding the lock for the whole time.

I'm going to tackle it, once the RPC branch is in.

### LINKED ISSUE #94: LOCK properly, everywhere, where necessary
Locks are used to ensure not more than one thread at the time enters a "locked" region, for example to prevent that thread A writes some data, and another thread B (for example UI, RPC) reads at that moment.

Currently there are a few places where `LOCKs` are likely missing.

The following parts should be guarded:

- global state objects
- pending transaction objects
- caches

The lock we currently use is `cs_tally`, whereby I think it would make sense to use a seperated one for the pending transaction objects, and probably for the caches, especially the UI-only caches, too.

### PR DESCRIPTION
**Pull request by dexX7**
This is a first take to resolve #85 and to resolve #94.

No RPC call uses the "is not threadsafe" flag anymore, which locks `cs_main` and `cs_wallet`. Locks are instead used more targeted.

I coded a script to call random "passive" commands, like `listtransactions_MP()`, and I'm running it for some time now in multiple threads, while also running the RPC tests, to pin down potential issues.

Right now all this isn't ideal, it disturbs the code flow, and not everything is locked, when it should be, like many `getSP()` - primarily, because doing so yielded (very rare) deadlock warnings. I'm also not yet convinced there is no risk of deadlocks after this PR.

While it would certainly make sense to move the locks into methods like `getSP()` at some point, I don't feel comfortable enough to do so yet, mostly due to the handler locks, which many other parts.

### CODE REVIEW

**Comment by dexX7** [comment]
After ~4.5 hours on mainnet, and bombing the server with 9 seperated RPC clients: no deadlocks, and the commands go still through, even while requesting 5000+ transactions `listtransactions_MP` *and* sending sends via the UI at the same time. :)

**Comment by zathras-crypto** [comment]
This is great dude!  Reviewed, looks fine to me...  So it seems all our RPC commands would be considered thread safe with this PR :)

Do you want to merge this in so I can bring it into my MetaDEx RPC branch?

**Comment by dexX7** [comment]
> would be considered thread safe with this PR

Let's hope so! Hehe.. we'll see. From an user's perspective threadsafety isn't really notable, but with this PR no command is blocking anymore, too. :)

Please don't worry too much, if you're going to tackle the RPC/MetaDEx branch tough, and you may just ignore lock. I have to think further about it anyway, and the new structure is so much easier to deal with anyway. :)

**Comment by zathras-crypto** [comment]
I'm seeing a blank tx history with this merged in mate, I'm trying to diagnose now :)

**Comment by zathras-crypto** [comment]
> I'm seeing a blank tx history with this merged in mate, I'm trying to diagnose now :)

Ahhhh nevermind - disregard mate.  Just released that with the change of marker every Class C test transaction we've sent on testnet no longer counts hehe.  I should have spotted that sooner, d'oh!!!

**Pull request merged**
