### PR TITLE
Update seed blocks until block 380000

### PR DESCRIPTION
**Pull request by dexX7**
This updates the seed blocks until block 380000.

The last seed block is 379999.

The updated set of seed blocks contains only those blocks, which contain *valid* Omni transactions. Invalid Omni transactions are not included.

When comparing the old set with the updated set, based on the old boundaries (max. block: 369999), then the updated set contains less blocks than the old set. This is is likely caused by only considering valid Omni transactions.

To confirm, reparse Omni transactions, disable block skipping and dump consensus hashes:
```
omnicored -startclean -omniseedblockfilter=0 -omnidebug=consensus_hash_every_block
```

Then extract the consensus hashes and start with enabled seed blocks:
```
omnicored -startclean -omnidebug=consensus_hash_every_block
```

Finally compare the previous hashes with the new consensus hashes.

### CODE REVIEW

**Comment by dexX7** [comment]
A few more notes, given that we don't have a mechanism to generate the seed block list, and neither a well defined process for the verification.

I used [this](http://pastebin.com/NhjxaJ2H) rather hacky patch to generate the list with:
```
omnicored -startclean -omniseedblockfilter=0 -omnidisablelegacy
```

This isn't optimal, because with `-omnidisablelegacy` a different path in consensus critical code is used. While I'm convinced the results should be similar, it's worth to note nevertheless.

However, I tested the following to confirm the new list is valid:

1. Add the new checkpoint from #274, then use the updated list, and check whether it passes successfully with `-startclean`. This could be considered as lightweight consensus check up to block 380000.

2. Locally merge #226 to have checkpoints for the whole state, then use the updated list, and check whether it also passes successfully with `-startclean`. This could be considered as more heavy consensus check up to block 370000.

I didn't verify the checkpoints of #226, and because I only used the checkpoins from #226, there are unchecked gaps (namely the blocks without checkpoint), and the last checkpoint of #226 was for block 370000, while the full seed block list ends at block 380000.

For a full blown verification of the seed block list, the following steps might be needed:

1. merge #226 into main branch
2. start clean, with disabled seed block filter
3. dump every consensus hash
4. extract the hashes
5. repeat, but with enabled seed block filter
6. then compare the hashes

@zathras-crypto: what do you think? I really wouldn't mind to postpone this PR until after the release, but on the other hand, even the lightweight checks may be sufficient, given that the generation of the seed blocks is pretty straight forward.

**Comment by dexX7** [comment]
Ah, and another note regarding valid/invalid transactions:

When the seed block list contains only blocks with valid Omni transactions, and blocks with invalid Omni transactions are skipped, then a user who sent invalid Omni transactions at some point in the past probably won't see them in the UI.

I wouldn't consider this as an issue though.

**Comment by zathras-crypto** [comment]
> Invalid Omni transactions are not included.

I think this is a little too restrictive - IIRC when I did the seed block list I also included Omni transactions *that were structurally valid* but were invalid because of say insufficient balance.  Long story short if they would be written to LevelDB txdb they were added to the seed block list (criteria for levelDB is a structurally valid, but not necessarily state valid transaction).

Without this calls like ```omni_gettransaction``` won't work for state-invalid transactions.

> @zathras-crypto: what do you think?

Your patch looks good dude, mine was a little more 'ghetto' about the collection of the data hehe - I hooked into where we write the tx to levelDB and then pushed the block to console, scraped and removed the duplicates.  Adding to a ```std::set``` would be a much better idea as that would handle the duplicates automatically, but I did it quite quickly as a manual thing so wasn't the cleanest.  

Since we need a repeatable process anyway, perhaps we could add a defined process and a startup flag to generate the seedblocks?

> I really wouldn't mind to postpone this PR until after the release

I don't see the need to wait until after the release since seed blocks are low hanging fruit and provide such a significant boost in initial parsing (ie improving the first "experience" users get with the product).

**Comment by dexX7** [comment]
> I think this is a little too restrictive - IIRC when I did the seed block list I also included Omni transactions that were structurally valid but were invalid because of say insufficient balance.

Interesting point, this approach sounds very reasonable to me. We also need to take care of Exodus purchases and DEx payments, but that's probably clear anyway.

> Since we need a repeatable process anyway, perhaps we could add a defined process and a startup flag to generate the seedblocks?

+1

We'd probably need to insert a hook somewhere, then check, whether a block was previously "seen", and ideally write/append the block to a file (which seems more straight forward then abusing the log).

> I don't see the need to wait until after the release since seed blocks are low hanging fruit and provide such a significant boost in initial parsing (ie improving the first "experience" users get with the product).

Well, I guess it really comes down to the priorities. Based on my understanding the RC should have been out yesterday, so if we start with tackling the seedblock generation now, it probably creates more delays.

**Comment by zathras-crypto** [comment]
> Well, I guess it really comes down to the priorities. Based on my understanding the RC should have been out yesterday, so if we start with tackling the seedblock generation now, it probably creates more delays.

Yeah I'd definitely agree with not slowing down the release process for it - I figure the "process" where we build in something repeatable with a flag and so on can wait until after release, but I think we can get the seedblocks in manually straight away.  I'd rather not merge this one as is due to it leaving out invalid transactions, but I could generate a new seedblock list today up to 380,000 which you could then double check and merge in so we don't have a hold-up perhaps?

**Comment by dexX7** [comment]
> I'd rather not merge this one as is due to it leaving out invalid transactions, but I could generate a new seedblock list today up to 380,000 which you could then double check and merge in so we don't have a hold-up perhaps?

Perfect, thanks! :) I'll close this one then.

**Pull request closed without merging**
