### PR TITLE
Move project files into src/omnicore

### PR DESCRIPTION
**Pull request by dexX7**
As result of the previous discussion, this PR moves the Omni Core files into `src/omnicore` and `src/omnicore/test`, without `mastercore_` or `omnicore_` file prefix.

Additional grouping within the subdir would probably make sense, and in the longer run I could imagine to split files and have less classes per file, for example in the case of the traditional DEx and meta DEx, or to have a dedicated file solely for transaction decoding, and another one for the actual logic.

I wouldn't prioritize this, but it should visualize the changes and the file structure:

- https://github.com/dexX7/bitcoin/tree/oc-0.10-project-move-subdir/src/omnicore

The QT files should probably live in `src/omnicore/qt`, but I'm not 100 % sure at this point, how well this can be integrated.

Alternatively, it could also be possible to move the files early, then integrate #13, but leave all UI and QT files in `src/qt`, to reduce the impact, and address it later. Nevertheless it would be required to update the `mastercore_` references, and maybe resolve other conflicts.

While I could convert #13, I assume getting this in significantly affects the UI development, and unless @zathras-crypto thinks it would absolutely be no issue, I suggest to just move the discussion from #15 to this place, and postpone the actual move, given that it's only "nice to have", but without immediat gain.

### CODE REVIEW

**Comment by zathras-crypto** [comment]
Sorry, must have missed commenting on this - I support the idea - re the UI I don't think it would be too much of a hardship to fix that up to respect the new naming convention :)

**Comment by dexX7** [comment]
I'd like to postpone this PR until #13 was merged, and ideally `mastercore_dex` was split into `mastercore_dex` and `mastercore_mdex`.

To resolve the conflicts here, I have to go though the steps anyway, which doesn't take long, but it would break again, once either one of the above takes place, thus "on hold".

**Comment by dexX7** [comment]
Updated, but I tend to enqueue this after the UI integration, given the conflicts it introduces.

**Comment by dexX7** [comment]
@zathras-crypto: given that the UI branch was merged, it's probably a good time to merge this one too. Do you agree?

**Comment by zathras-crypto** [comment]
> given that the UI branch was merged, it's probably a good time to merge this one too. Do you agree?

Sorry bud I've been slack on this one - I haven't actually had a chance to look at what's required to move the UI files to /src/omnicore/qt yet

**Comment by dexX7** [comment]
Currently only the `src/mastercore*`, `src/omnicore*` and `src/test/mastercore*` files are moved, while the the QT files are still in `src/qt/`, which is fine, I guess, and it could be done later, but I haven't really made up my mind how the secondary files (e.g. the images etc.) could fit into this nicely.

I mentioned the UI PR, because it touched many files, and many of them were affected by the `src/ -> src/omnicore/` move.

**Comment by zathras-crypto** [comment]
Ah OK then - no objections here :)

**Comment by zathras-crypto** [comment]
Sorry, accidental close there :(

**Comment by dexX7** [comment]
Haha, no worries. :)

**Pull request merged**
