### PR TITLE
Skip loading unneeded blocks during initial parsing

### PR DESCRIPTION
**Pull request by zathras-crypto**
WIP.  PR to trigger running the tests.

### CODE REVIEW

**Comment by dexX7** [comment]
Hm, I hoped merging the PR, no which this one is build would be detected by GitHub.

Please rebase this PR as follows:
```bash
~/omnicore$ git fetch upstream omnicore-0.0.10
~/omnicore$ git checkout omnicore-0.0.10
~/omnicore$ git pull upstream omnicore-0.0.10
~/omnicore$ git checkout 0.0.10-Z-DexX-TestSkipBlockList
~/omnicore$ git rebase omnicore-0.0.10
```

**Comment by dexX7** [comment]
I tend to hold back this PR until the very end, because it greatly reduces the potential of the consensus tests run on the CI server?

**Comment by dexX7** [comment]
```c++
PrintToConsole("%s(): to insert %d elements: %.4f ms\n", __func__, blockList.size(), 0.001 * nTime);
```
Should probably be replaced by something like:
```c++
PrintToLog("%s(): going to skip %d blocks [loading time: %.4f ms]\n", __func__, blockList.size(), 0.001 * nTime);
```
... or similar.

**Comment by zathras-crypto** [comment]
> I tend to hold back this PR until the very end, because it greatly reduces the potential of the consensus tests run on the CI server?

This PR was really only just to trigger the consensus tests to see if my new block list was good :)

Can you explain what you mean about reducing potential for consensus tests on CI?

**Comment by dexX7** [comment]
The CI server currently starts fresh, and parses all Omni transactions. If we apply this PR, then certain blocks are skipped, and errors, we may have introduced, may be undetected.

Rephrased: parsing with enabled skipping is less thorough.

Alternatively, and I think this would be useful in general, we could add an option/flag to disable skipping.

**Comment by zathras-crypto** [comment]
> The CI server currently starts fresh, and parses all Omni transactions. If we apply this PR, then certain blocks are skipped, and errors, we may have introduced, may be undetected.

Ahh I see what you mean.

> Alternatively, and I think this would be useful in general, we could add an option/flag to disable skipping.

Yeah, we'll absolutely add a ```--seedblockfilter=false``` so users can opt-out - could the CI jobs just be adjusted to run with this flag?

**Comment by dexX7** [comment]
Yes! :)

Maybe it should be `-omnixxxxx` though.

**Comment by zathras-crypto** [comment]
Interesting - adding commits didn't trigger CI this time?

**Comment by dexX7** [comment]
After I realized I pushed a PR, which was going to fail due to the missing `rules.h` include, I stopped the pending Travis jobs (which were going to fail, as consequence of the failing base).

Looks like this also prevented that new pushes triggered new builds.

Check out: https://travis-ci.org/OmniLayer/omnicore/pull_requests

The grey ones can be restarted (actually any job) in the detail view with a click on the restart/replay button:

replay

**Comment by zathras-crypto** [comment]
I see now yep thanks - assume you already pushed the button :)

**Comment by dexX7** [comment]
Something seems to be broken:

https://travis-ci.org/OmniLayer/omnicore/jobs/71184933#L2533

Though it's nearly impossible it has anything to do with this PR.

**Comment by dexX7** [comment]
Mainnet consensus is fine by the way.

**Comment by zathras-crypto** [comment]
> Mainnet consensus is fine by the way.

Nice, so the new block list is good then I believe - now we just need to decide how we want to code the list in...

**Comment by dexX7** [comment]
> Nice, so the new block list is good then I believe - now we just need to decide how we want to code the list in...

I suggest to revert the `AddBlockStr()` stuff, given that this was created based on a misunderstanding/miscommuncation from my side.

Other than that, I'm not really sure what to add here. We could just use the string based list and refine later, or try to find an alternative. On the other hand, this would be purely cosmetic, given that even the cluttered string based list is processed within milliseconds.

From another perspective: do you see any risk/potential pitfalls with this approach in general?

**Comment by zathras-crypto** [comment]
> I suggest to revert the AddBlockStr() stuff, given that this was created based on a misunderstanding/miscommuncation from my side.

I think it was me who misunderstood mate :)  

Reverted and updated the blockString in https://github.com/zathras-crypto/omnicore/commit/3c05139834a8538013d11e15ae1ecee0d34094e1

> From another perspective: do you see any risk/potential pitfalls with this approach in general?

Nope, it is purely cosmetic as you note and if we want to refine it we can do so at a later date, for now it does the job it needs to do.

**Comment by zathras-crypto** [comment]
> Looks like this also prevented that new pushes triggered new builds.

I'm not quite sure why but seems this is still the case - that last commit didn't trigger a Travis run, I checked on the dashboard and the last build for this PR was 362 which was successful.

**Comment by dexX7** [comment]
> I'm not quite sure why but seems this is still the case ...

I'm not sure either. Tried to manually start it a few seconds ago.

I'm going to take another look at this PR, and see, if we can create some kind of structure with starting height, end height, network and the block list - hopefully later.

Other than that, I wouldn't say I have a bad feeling, especially because I trust in tests and if we don't touch the parsing code (and introduce bugs), then this *will* produce the same results. Nevertheless, I'd feel more comfortable, once we have consensus checkpoints. This however, is something for the future, and it shouldn't hold back this PR.

So my plan:

- [x] Update OmniJ (pending, but initiated)
- [ ] Another code check and thinking it through
- [ ] Potentially minimal refactoring

**Comment by dexX7** [comment]
Do you think it would make sense to wrap the block list into a signed message, say signed with 1Exodus, to ensure the data isn't tampered?

**Comment by dexX7** [comment]
I haven't tested it on mainnet, but compilation works fine, without huge memory consumption spike:

```c++
static std::set<int> GetBlockList()
{
    int blocks[] = {249498, 249536, 249559, 249560, /* ... */ 365219};
    return std::set<int>(blocks, blocks + sizeof(blocks)/sizeof(blocks[0]));
}
```

**Comment by dexX7** [comment]
I'd really like to introduce a structure similar to `CChainParams` in the future, to handle some base information for different networks. This could then include the block list (and eventually consensus rules/activations).

At this point though, I'm not really sure how to start, so I suggest to continue with the current version of this PR (potentially with the change of https://github.com/OmniLayer/omnicore/pull/135#issuecomment-123912157), and then restructure later.

As alternative to a signed block list, do you think it would be possible (and cheap) to determine the number of valid transactions at any given point? If so, we may add at least some kind of checkpoint, where the number of valid transactions (after scanning) is compared against an expected value?

**Comment by zathras-crypto** [comment]
> Do you think it would make sense to wrap the block list into a signed message, say signed with 1Exodus, to ensure the data isn't tampered?

If we were going to do this it should be a hash, not the entire block list because the list is almost 100,000 bytes already and we'd probably draw some negative heat for putting such a large (what some vocal people will call spam) transaction on the chain.  Plus we'd want to be able to update the list in the future.  With that said though, I don't really see much value to this because if someone has the ability to tamper with the source code there are much more useful modifications to make than adding/removing skipped blocks (such as redirecting funds or sending  keys to remote servers etc etc).

> I haven't tested it on mainnet, but compilation works fine, without huge memory consumption spike:

Oh nice, that sounds like it could be a good method - any reason not to go this way?

> I'd really like to introduce a structure similar to CChainParams in the future, to handle some base information for different networks. This could then include the block list (and eventually consensus rules/activations).

I think this would be a good idea, but I'm not intimately familiar with CChainParams so would need to research/review that a bit - but yep certainly could be a direction for the future, no objections from me there...

> we may add at least some kind of checkpoint, where the number of valid transactions (after scanning) is compared against an expected value?

I have some random thoughts in this area, let me try and make them coherent and I'll reply properly to this later with some bits of code I have too :)

**Comment by dexX7** [comment]
> Oh nice, that sounds like it could be a good method - any reason not to go this way?

I'd say, let's go with it. I just wanted to point out that I just tested it locally without chain.

> I have some random thoughts in this area, let me try and make them coherent and I'll reply properly to this later with some bits of code I have too :)

See, my point is basically the following: you published a block list, and I trust you, and I believe you didn't tamper the list, but how could I *know* this is the right list (and no block with DEx payment was accidently left out, which wasn't detected by the consensus tests for any reason, just to name an example)?

If I, as maintainer, am not able to answer this question properly, then I don't have a good feeling of publishing the list without any safe guard/integrity check/[...]. Is there a handy way to reproduce the list? If so, we should point that out as comment.

**Comment by zathras-crypto** [comment]
>> we may add at least some kind of checkpoint, where the number of valid transactions (after scanning) is compared against an expected value?

> I have some random thoughts in this area, let me try and make them coherent and I'll reply properly to this later with some bits of code I have too :)

Let me know what you think of #145 when you have a spare mo mate, and whether this goes towards helping with concerns over the block list...

**Comment by dexX7** [comment]
> Let me know what you think ...

I love it! :)

My last open question/remark: how was the block list created?

**Comment by zathras-crypto** [comment]
> how was the block list created?

Nothing particularly brilliant mate hehe, just a bunch of ```printf```'s scattered throughout the code to dump the block numbers for various bits during a full parse from scratch with the output pumped into ```sort``` & ```uniq```.

**Comment by dexX7** [comment]
@zathras-crypto: OmniJ was updated. Could you try https://github.com/OmniLayer/omnicore/pull/135#issuecomment-123912157, if you find some time? :)

I suggtest to merge #145 (once empty entries are skipped), then this one.

**Comment by zathras-crypto** [comment]
> Could you try #135 (comment), if you find some time? :)

Sure! :)  But I think I broke something hehe...  At least the new stuff from #145 is doing its job...  I'm investigating further now but have a plane to catch so might take a little while...

```
$ src/omnicored --server --daemon --checkblocks=1 --startclean
Omni Core server starting
2015-07-26 06:20:07 Initializing Omni Core v0.0.9.99-dev [main]
2015-07-26 06:20:07 Loading trades database: OK
2015-07-26 06:20:07 Loading send-to-owners database: OK
2015-07-26 06:20:07 Loading transactions database: OK
2015-07-26 06:20:07 Loading smart property database: OK
2015-07-26 06:20:07 Loading persistent state: NONE
2015-07-26 06:20:07 Scanning for transactions in block 249498 to block 360003..
Error: Shutting down due to failed checkpoint for block 270000 (hash 0000000000000002a775aec59dc6a9e4bb1c025cf1b8c2195dd9dc3998c827c5)
2015-07-26 06:20:15 Scan stopped early at block 270001 of block 360003
2015-07-26 06:20:15 363731 transactions processed, 639 meta transactions found
2015-07-26 06:20:15 Exodus balance: 7648.97980178 MSC
2015-07-26 06:20:15 Omni Core initialization completed
2015-07-26 06:20:15 Omni Core shutdown completed

$ tail -100 ~/.bitcoin/omnicore.log | grep -i verifycheckpoint
2015-07-26 06:20:15 VerifyCheckpoint(): consensus hash mismatch - expected 486a81cb5b0c89d26543e85f2635f225468e87bda89e752ab2dcebf1d2f74248, received 4eb6f75c961308c18dad1e2677170465f30d367489e61cb2510e400dc3d21117
```

**Comment by zathras-crypto** [comment]
Even more interesting (note seed block filter disabled):
```
$ src/omnicored --server --daemon --checkblocks=1 --startclean --omniseedblockfilter=false
Omni Core server starting
rich@lenlaptop:~/github/build/omnicore$ 2015-07-26 06:39:53 Initializing Omni Core v0.0.9.99-dev [main]
2015-07-26 06:39:53 Loading trades database: OK
2015-07-26 06:39:53 Loading send-to-owners database: OK
2015-07-26 06:39:53 Loading transactions database: OK
2015-07-26 06:39:53 Loading smart property database: OK
2015-07-26 06:39:53 Loading persistent state: NONE
2015-07-26 06:39:53 Scanning for transactions in block 249498 to block 360003..
2015-07-26 06:40:23 Still scanning.. at block 255315 of 360003. Progress: 3.42 %, about 14:03 minutes remaining..
2015-07-26 06:40:53 Still scanning.. at block 261212 of 360003. Progress: 6.77 %, about 13:44 minutes remaining..
2015-07-26 06:41:23 Still scanning.. at block 267242 of 360003. Progress: 9.95 %, about 13:33 minutes remaining..
Error: Shutting down due to failed checkpoint for block 270000 (hash 0000000000000002a775aec59dc6a9e4bb1c025cf1b8c2195dd9dc3998c827c5)
```

**Comment by zathras-crypto** [comment]
Note, this may be down to the exclusion of empty balances, and I may need to regenerate the checkpoints...  Will report back...

**Comment by zathras-crypto** [comment]
Alrighty, it's definitely the change to filter empty entries from the consensus hash.  What's got me confused is why Travis didn't pick this up, the CI build would have aborted at block 270000 during parsing for the consensus tests due to a failed checkpoint.

Anywho, the fix is simple, I've generated some new checkpoints based on the new consensus hashing code that filters empty balances.

> Could you try #135 (comment), if you find some time? :)

The good news is the probs were related to the empty balances change to consensus hashing, and seed block filtering gives identical hashes to when parsing without the seed block filter.  When I pushed the new checkpoints and ran the updated method again all was well so TL:DR; all good!  (https://github.com/zathras-crypto/omnicore/commit/6c15e2d97c70f7506f4a335a01e6f7714aa71171)

**Comment by dexX7** [comment]
>  What's got me confused is why Travis didn't pick this up, the CI build would have aborted at block 270000 during parsing for the consensus tests due to a failed checkpoint.

Hm? We only run regtests with Travis, and no consensus tests for pull requests (unfortunally). Once a PR is merged, then a build is triggered on https://ci.omni.foundation.

**Comment by zathras-crypto** [comment]
Ahhh that actually explains a lot - I had it in my head that Travis also
ran consensus testing - thanks for the clarification.

**Comment by dexX7** [comment]
Unfortunally Travis doesn't do this. With block skipping we may actually have enough time to parse the initial transactions (about 10 minutes for regtests, 15-20 minutes for mainnet - limit is 50 minutes), but Travis has no fully synched chain.

A crazy idea might be to store a copy of the blockchain on S3, and download it via Travis, but I wouldn't consider this as feasible or reasonable solution, especially given that we *have* a CI server. :)

It actually is possible to trigger Jenkins jobs (-> consensus tests) with pull requests, but unfortunally this isn't configured (yet? @msgilligan).

**Comment by zathras-crypto** [comment]
Note, this PR passes all checkpoints - given this is such a huge improvement for new users (a 4 minute first-run-startup rather than ~40 mins is a great boost to usability imo), what else is needed to merge?  

Perhaps a final checkpoint following the last seed block in the list?

```
$ src/omnicored --server --daemon --checkblocks=1 --startclean 
Omni Core server starting
2015-07-28 00:31:41 Initializing Omni Core v0.0.9.99-dev [main]
2015-07-28 00:31:41 Loading trades database: OK
2015-07-28 00:31:41 Loading send-to-owners database: OK
2015-07-28 00:31:41 Loading transactions database: OK
2015-07-28 00:31:41 Loading smart property database: OK
2015-07-28 00:31:41 Loading persistent state: NONE
2015-07-28 00:31:41 Scanning for transactions in block 249498 to block 360019..
2015-07-28 00:32:11 Still scanning.. at block 278985 of 360019. Progress: 18.38 %, about 2:10 minutes remaining..
2015-07-28 00:32:41 Still scanning.. at block 297055 of 360019. Progress: 31.84 %, about 2:07 minutes remaining..
2015-07-28 00:33:11 Still scanning.. at block 309667 of 360019. Progress: 41.49 %, about 2:06 minutes remaining..
2015-07-28 00:33:41 Still scanning.. at block 321552 of 360019. Progress: 51.45 %, about 1:52 minutes remaining..
2015-07-28 00:34:11 Still scanning.. at block 332154 of 360019. Progress: 62.62 %, about 1:29 minutes remaining..
2015-07-28 00:34:41 Still scanning.. at block 340016 of 360019. Progress: 72.27 %, about 1:08 minutes remaining..
2015-07-28 00:35:11 Still scanning.. at block 349196 of 360019. Progress: 84.18 %, about 39 seconds remaining..
2015-07-28 00:35:41 Still scanning.. at block 357318 of 360019. Progress: 95.92 %, about 10 seconds remaining..
2015-07-28 00:35:54 8851804 transactions processed, 22998 meta transactions found
2015-07-28 00:35:54 Exodus balance: 16272.87369810 MSC
2015-07-28 00:35:54 Omni Core initialization completed
```

**Comment by dexX7** [comment]
> Note, this PR passes all checkpoints - given this is such a huge improvement for new users (a 4 minute first-run-startup rather than ~40 mins is a great boost to usability imo), what else is needed to merge?

Nothing in my opinion. :)

The checkpoints paved the way for this PR. I could imagine we add the no-skip-blocks to the consensus params, and make them fully network aware (i.e. mainnet, testnet, ...), and adding a checkpoint for the last block in the list wouldn't hurt either, but all this can be done in one or more subsequent PRs.

**Comment by zathras-crypto** [comment]
> Nothing in my opinion. :)

Awsome, am about to redo the preview builds with the testnet trading fix in, and was hoping to get this merged in prior :)

**Comment by dexX7** [comment]
Yep, I saw your gitian.sigs. :)

I'll be out this day, and back in around 6 hours. Then I'm going to fire up my notebook and start building. Luckliy I have the Gitian images already installed.

I updated the temporary changelog:

- https://github.com/OmniLayer/omnicore/issues/96#issuecomment-119294812

A very small rant:

I'd feel more comfortable, if releases are not rushed. I have the impression we're at 40 % most of the time, but one, or two days before a build the pace switches to "should have been yesterday". Would probably be better to schedule a (pre-) release, and then get all outstanding PRs in, prepare the builds etc.

**Pull request merged**
