### PR TITLE
Move test scripts into /src/omnicore/test

### PR DESCRIPTION
**Pull request by dexX7**
This pull request moves the test scripts from `test/` into `src/omnicore/test`.

### CODE REVIEW

**Comment by dexX7** [comment]
@zathras-crypto: I further noticed two things:

1. There are new files generated named `nul` and `null`. I saw some `> nul` and `> null`. Should I replace them with `> /dev/null`?

2. The test `test_fees.sh` currently fails more me, because the initial distribution isn't as expected.

**Comment by zathras-crypto** [comment]
> There are new files generated named nul and null. I saw some > nul and > null. Should I replace them with > /dev/null?

D'oh - too much Windows...  They should be replaced with /dev/null yeah...

> The test test_fees.sh currently fails more me, because the initial distribution isn't as expected.

That test requires devmsc to be disabled (noted at the top of the test) - this is really scrappy but I didn't see a way around it...

**Comment by dexX7** [comment]
Oh my bad, I should have read it once more, haha.

I'm going to update the dev null stuff.

**Comment by dexX7** [comment]
Updated.

The scripts should be executed from within `./omnicore/`.

**Comment by zathras-crypto** [comment]
Tested & confirmed tests still work fine, feel free to merge at your convenience bud :)

**Pull request merged**
