### PR TITLE
Harden and heavily log core logic

### PR DESCRIPTION
**Pull request by dexX7**
The unused parts related to transaction logic or interpretation, and especially the unused `step_n` methods are removed.

The scope and visibility of logic methods is reduced, to prevent "accidental logic execution". ;)

All failures during the core logic execution, except the ones one layer deeper (`DEx_offerUpdate`, `MetaDEx_ADD`, ...), are logged, including the values, which contribute to the failure.

Assertions are used, where applicable.

Failures, which are not based on malformed transactions, are tagged with `"ERROR"`. This is only the case, if a block hash, used to update properties, can't be retrieved from `chainActive`.

Failures, which are related to state and logic, are tagged with "rejected".

It would make sense to return error codes, or error flags, and move the logging outside of the core logic, but this could be something for a follow up PR. It would also be great to log successful/valid transactions in greater detail, because when going through the log, it's entierly clear, which transactions are new, valid, etc.. mostly due to the `parseTransaction` logging, which is also triggered by RPC calls.

The following rejection messages are logged:
```c++
logicMath_SimpleSend:
 - "type %d or version %d not permitted for property %d at block %d"
 - "value out of range or zero: %d"
 - "property %d does not exist"
 - "sender %s has insufficient balance of property %d [%s < %s]"

logicMath_SendToOwners:
 - "type %d or version %d not permitted for property %d at block %d"
 - "value out of range or zero: %d"
 - "property %d does not exist"
 - "sender %s has insufficient balance of property %d [%s < %s]"
 - "no other owners of property %d [owners=%d <= 0]"
 - "sender %s has insufficient balance of property %d to pay for fee [%s < %s]"
 - "sender %s has insufficient balance of %d to pay for amount + fee [%s < %s + %s]"

logicMath_TradeOffer:
 - "type %d or version %d not permitted for property %d at block %d"
 - "value out of range or zero: %d"
 - "property for sale %d must be MSC or TMSC"
 - "sender %s has no active sell offer for property: %d"
 - "sender %s has an active sell offer for property: %d"
 - "sender %s has no active sell offer for property: %d"

logicMath_AcceptOffer_BTC:
 - "type %d or version %d not permitted for property %d at block %d"
 - "value out of range or zero: %d"

logicMath_MetaDExTrade:
 - "type %d or version %d not permitted for property %d at block %d"
 - "property for sale %d and desired property %d must not be equal"
 - "property for sale %d and desired property %d not in same ecosystem"
 - "property for sale %d does not exist"
 - "desired property %d does not exist"
 - "amount for sale out of range or zero: %d"
 - "desired amount out of range or zero: %d"
 - "one side of a trade [%d, %d] must be MSC or TMSC"
 - "sender %s has insufficient balance of property %d [%s < %s]"

logicMath_MetaDExCancelPrice:
 - "type %d or version %d not permitted for property %d at block %d"
 - "property for sale %d and desired property %d must not be equal"
 - "property for sale %d and desired property %d not in same ecosystem"
 - "property for sale %d does not exist"
 - "desired property %d does not exist"
 - "amount for sale out of range or zero: %d"
 - "desired amount out of range or zero: %d"

logicMath_MetaDExCancelPair:
 - "type %d or version %d not permitted for property %d at block %d"
 - "property for sale %d and desired property %d must not be equal"
 - "property for sale %d and desired property %d not in same ecosystem"
 - "property for sale %d does not exist"
 - "desired property %d does not exist"

logicMath_MetaDExCancelEcosystem:
 - "type %d or version %d not permitted for property %d at block %d"

logicMath_CreatePropertyFixed:
 - "invalid ecosystem: %d"
 - "type %d or version %d not permitted for property %d at block %d"
 - "value out of range or zero: %d"
 - "invalid property type: %d"
 - "property name must not be empty"

logicMath_CreatePropertyVariable:
 - "invalid ecosystem: %d"
 - "type %d or version %d not permitted for property %d at block %d"
 - "value out of range or zero: %d"
 - "property %d does not exist"
 - "invalid property type: %d"
 - "property name must not be empty"
 - "deadline must not be in the past [%d < %d]"
 - "sender %s has an active crowdsale"

logicMath_CloseCrowdsale:
 - "type %d or version %d not permitted for property %d at block %d"
 - "property %d does not exist"
 - "sender %s has no active crowdsale"
 - "property identifier mismatch [%d != %d]"

logicMath_CreatePropertyMananged:
 - "invalid ecosystem: %d"
 - "type %d or version %d not permitted for property %d at block %d"
 - "invalid property type: %d"
 - "property name must not be empty"

logicMath_GrantTokens:
 - "type %d or version %d not permitted for property %d at block %d"
 - "value out of range or zero: %d"
 - "property %d does not exist"
 - "property %d is not managed"
 - "sender %s is not issuer of property %d [issuer=%s]"
 - "no more than %s tokens can ever exist [%s + %s > %s]"

logicMath_RevokeTokens:
 - "type %d or version %d not permitted for property %d at block %d"
 - "value out of range or zero: %d"
 - "property %d does not exist"
 - "property %d is not managed"
 - "sender %s has insufficient balance of property %d [%s < %s]"

logicMath_ChangeIssuer:
 - "type %d or version %d not permitted for property %d at block %d"
 - "property %d does not exist"
 - "sender %s is not issuer of property %d [issuer=%s]"
 - "sender %s has an active crowdsale"
 - "receiver is empty"
 - "receiver %s has an active crowdsale"

logicMath_Alert:
 - "invalid transaction version: %d"
 - "sender %s is not authorized for alerts"
 - "failed to parse values: %s"
```

### CODE REVIEW

**Comment by zathras-crypto** [comment]
Note, I think we should stop logging when we parse via RPC :)

**Comment by zathras-crypto** [comment]
Great stuff and helpful logging here - reviewed, looks good to me, merge at your convenience mate :)

**Comment by dexX7** [comment]
Should the `creation_block` be set for managed properties, or the `creation_block` and `update_block`, similar to unmanaged properties and crowdsales?

**Comment by zathras-crypto** [comment]
```update_block``` should equal ```creation_block``` at the beginning :)

**Pull request merged**
