### PR TITLE
Format, document and add aggregation methods to CMPTally

### PR DESCRIPTION
**Pull request by dexX7**
The behavior of `CMPTally` is unchanged, but it's extended with:

```c++
/** Returns the number of available tokens. */
int64_t getMoneyAvailable(uint32_t propertyId) const;

/** Returns the number of reserved tokens. */
int64_t getMoneyReserved(uint32_t propertyId) const;

/** Compares the tally with another tally and returns true, if they are equal. */
bool operator==(const CMPTally& rhs) const;

/** Compares the tally with another tally and returns true, if they are not equal. */
bool operator!=(const CMPTally& rhs) const;
```

### CODE REVIEW

**Comment by dexX7** [comment]
There a few points, which might be discussed:

1. `update_tally_map()` returns `false`, if the amount to update is `0`, however, this isn't the case for `updateMoney()`, and a zero update is considered as successful money update. I think it should indicate failure, too.

2. Currently there are no checks to guarantee that the sum of reserved balances is < INT64_MAX. Since it's consensus affecting, I haven't implemented them, but maybe we should?

3. The logic around pending balances is completely focused on negative pending tally amounts. Should we consider there could be positive pending amounts?

4. The balances are protected against overflows, but pending amounts are not, and right now it's possible to update the pending balance without limitations:
   ```c++
   updateMoney(propertyId, -9223372036854775808, PENDING); // pending = -9223372036854775808
   updateMoney(propertyId, -1, PENDING);                   // pending =  9223372036854775807 !
   ```

We have many checks in place to ensure this doesn't happen, but still, the more failsafes, the better in my opinion.

**Comment by zathras-crypto** [comment]
> update_tally_map() returns false, if the amount to update is 0, however, this isn't the case for updateMoney(), and a zero update is considered as successful money update. I think it should indicate failure, too.

We should not be calling balance changes for zero - I recall when I was experimenting with the auditor branch that it picked up some instances of zero valued updates.  So I kind of agree with your sentiment here.  With that said, as far as I can see ```updateMoney()``` is only used in a single location (within ```update_tally_map``` which returns false for zero amounts before getting to ```updateMoney()```) so at present there is no code path where ```updateMoney()``` can be called with zero amounts?

> Currently there are no checks to guarantee that the sum of reserved balances is < INT64_MAX. Since it's consensus affecting, I haven't implemented them, but maybe we should?

The more checks the better in my book - but then there is the case of what to do in that circumstance if it occurred?  There should be no way for any tally to >INT64_MAX because that would be exceeding the number of allowed tokens for a property.

> The logic around pending balances is completely focused on negative pending tally amounts. Should we consider there could be positive pending amounts?

Not in the near term I don't think.  Pending is an outbound concept only at the moment, meaning all amounts will be negative.  Inbound pending has massive implications which we're not ready to take on (definitely not for 0.0.10 anyway).  I still don't see any viable solution to inbound pending & the fact transaction ordering can never be known before a block is mined (add to that replace-by-fee seems to be gaining traction and even "first-seen" mining policy goes out the window).  Long story short - inbound pending is a large topic, and not one we want to take on for this release IMO.

> The balances are protected against overflows, but pending amounts are not, and right now it's possible to update the pending balance without limitations:

This would require the client to allow sending a transaction outside of bounds, but it's feasible of course - more checks are good with me :)

> We have many checks in place to ensure this doesn't happen, but still, the more failsafes, the better in my opinion.

That's a general feeling I would agree with all the way dude :)

Also, the PR itself looks fine to me, I wonder if your new tally compare operator would be faster than what I've got in ```walletcache.cpp``` where we "check cache for miss on balance"?

**Comment by dexX7** [comment]
> so at present there is no code path where updateMoney() can be called with zero amounts?

Ah, this is great. Then it's safe to return `false`, if there is ever an attempt to update a zero money value.

> The more checks the better in my book - but then there is the case of what to do in that circumstance if it occurred?

For money updates, which don't touch pending amounts, `updateMoney()` returns false, if `old amount + amount < 0`. While it's certainly a sanity check, it's also an overflow protection, because `INT64_MAX + 1 = INT64_MIN`. Rejecting the update seems sufficient in my opinion, at least in `updateMoney()`, given that it's pretty low level.

> Inbound pending has massive implications which we're not ready to take on 

Agreed.

> This would require the client to allow sending a transaction outside of bounds, but it's feasible of course - more checks are good with me :)

Alright. I'll add them at some point, and I agree it's the right thing to do. The only case where it could happen is some bug, which would break consensus between "overflow protected" and "non protected" clients. On the other hand, if there is some bug, which triggers an overflow of pending balances, then the state is already "broken" anyway.

> Also, the PR itself looks fine to me, I wonder if your new tally compare operator would be faster than what I've got in walletcache.cpp where we "check cache for miss on balance"?

This was actually the reason why I started it. :)

**Comment by zathras-crypto** [comment]
> This was actually the reason why I started it. :)

Heh, you rock dude :) thanks!

**Pull request merged**
