### PR TITLE
Update documentation of configuration options

### LINKED ISSUE #71: Documentation for Omni Core specific options
The following options should be documented:

- `-omnialertallowsender=source` (multi string, authorize alert senders, can be `any`)
- `-omnialertignoresender=source` (multi string, ignore alert senders)
- `-autocommit` (boolean, create or broadcast transactions, enabled by default)
- `-disclaimer` (boolean, explicitly show QT disclaimer on startup, disabled by default)
- `-omnidebug=category` (multi string, enable log categories, can be `all`, `none`)
- `-omnilogfile=file` (string, log file, `omnicore.log` by default)
- `-overrideforcedshutdown` (boolean, overwrite shutdown, triggered by an alert, disabled by default)
- `-startclean` (boolean, clear persistence files, disabled by default)
- `-omniprogressfrequency` (number, time in seconds after which the initial scanning progress is reported, 30 seconds by default)
- `-rpcforceutf8` (boolean, replace invalid UTF-8 encoded characters with question marks in RPC response, default: 1)
- `-omniuiwalletscope` (number, number of wallet transactions considered by the UI, default: 65535)

The options `-datacarrier` and `-datacarriersize` might be mentioned, given that those have an impact on whether class B or class C transactions are created.

Alternatively, and this is what I'd prefer, we add an explicit option to set the limit for class C transactions. I'd favor it, because this allows to use different values, and if we do this, I suggest to set the client's default relay value to 80 byte, but the default cutoff for class C transactions to 40 byte, to support larger `OP_RETURN` transactions, while ensuring the transactions created by Omni Core are not delayed. The size of 80 byte is the new default for Bitcoin Core 0.11, but I think we should have expressed "support" ideally yesterday.

### PR DESCRIPTION
**Pull request by dexX7**
The documentation of the configuration options was extended and updated.

This resolves #71 for the most part.

### CODE REVIEW

**Comment by dexX7** [comment]
I added tables here as well. To compare:

- [preview without tables](https://github.com/dexX7/bitcoin/blob/8e348315842361831944ac6ba1a845a84dfc1b30/src/omnicore/doc/configuration.md)
- [preview with tables](https://github.com/OmniLayer/omnicore/blob/a6427d0315af4d6d3274833dc11ddb38e16cd9b1/src/omnicore/doc/configuration.md)

**Comment by msgilligan** [comment]
Command-line options can also be documented with ... wait for it ... Asciidoctor! ... which has special support for [UNIX manual pages](http://asciidoctor.org/docs/user-manual/#man-pages).

It is used by Git (e.g. [git-clone]()) and by [asciidoctor](https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/man/asciidoctor.adoc) itself.

I used it to create the [bitcoinj-cli man page](http://msgilligan.github.io/bitcoinj-addons/manpage-bitcoinj-cli.html) -- [source](https://github.com/msgilligan/bitcoinj-addons/blob/master/doc/manpage-bitcoinj-cli.adoc) -- in [bitcoinj-addons](https://github.com/msgilligan/bitcoinj-addons).

**Comment by dexX7** [comment]
@msgilligan: please don't get me wrong, I'd really really like a rendered documentation, but I see it out of scope of the pending pull requests (mostly due to time/my current knowledge). I do think we should come to that point, but right now I have to decide whether to hold it back or merge, and I'm going with the latter, because "better is better" in my opinion.

**Comment by msgilligan** [comment]
Yeah, go ahead and merge.

I'm hoping to have time to help with rendered documentation sometime within the next month or so, but don't wait for me.

**Comment by dexX7** [comment]
Okay, great. Thanks for your "blessing"! :)

**Pull request merged**
