### PR TITLE
RPC: Standardize calls on omni_abcdefghij

### PR DESCRIPTION
**Pull request by zathras-crypto**
Note: All existing calls (```abcdefghij_MP```) have been aliased to provide backwards compatibility.

### CODE REVIEW

**Comment by dexX7** [comment]
Thanks, ACK!

I suggest seperate between "alias" calls and "other hidden" calls, because the first ones should be depreciated at some point.

Since they are already sort of categorized, it may make sense to introduce actual categories. What do you think? E.g. "omni layer" -> "omni layer transactions", or "creation"?

**Comment by zathras-crypto** [comment]
> I suggest seperate between "alias" calls and "other hidden" calls, because the first ones should be depreciated at some point.

Done, though I still think ```trade_MP``` can be removed right now.

> Since they are already sort of categorized, it may make sense to introduce actual categories. What do you think? E.g. "omni layer" -> "omni layer transactions", or "creation"?

Sure, done also.

I think this is ready, OK with you to merge?

**Comment by dexX7** [comment]
> Done, though I still think trade_MP can be removed right now.

Noted. /todo: finally update OmniJ

I'll switch to Ubuntu in a minute. PR looks good.

**Comment by dexX7** [comment]
A couple of colons were removed:
```diff
-            "\nExamples:\n"
+            "\nExamples\n"
```

... which I added manually back.

**Comment by zathras-crypto** [comment]
> A couple of colons were removed

Ahh sorry, I probably got a bit trigger happy while sorting the conflicts hehe :)

**Pull request merged**
