### PR TITLE
Unlock trading of all pairs on the MetaDEx

### PR DESCRIPTION
**Pull request by zathras-crypto**
This PR is intended to add support for activating trading of non-Omni pairs on the distributed exchange.

Feature ID 8 will be used to activate trading all pairs.  Prior to activation the current restrictions remain in place.

Note, this should really get merged in before fees ideally, it's a pretty clear cut PR but please shout if you see anything off.

There is a test script included that regtests the activation scenario.  Results from my run pasted below.

```
Preparing a test environment...
   * Starting a fresh regtest daemon with open activation sender
   * Preparing some mature testnet BTC
   * Obtaining a master address to work with
   * Funding the address with some testnet BTC for fees
   * Participating in the Exodus crowdsale to obtain some OMNI
   * Creating an indivisible test property
   * Creating a divisible test property

Testing a trade against self that uses Omni (1.1 OMNI for 20 #3)
   * Executing the trade
   * Verifiying the results
      # Checking the trade was valid...PASS

Testing a trade against self that doesn't use Omni to confirm non-Omni pairs are disabled (4.45 #4 for 20 #3)
   * Executing the trade
   * Verifiying the results
      # Checking the trade was invalid...PASS

Activating trading on all pairs
   * Sending the activation
     # Checking the activation transaction was valid...PASS
   * Mining 10 blocks to forward past the activation block
     # Checking the activation went live as expected...PASS

Testing a trade against self that doesn't use Omni to confirm non-Omni pairs are now enabled (4.45 #4 for 20 #3)
   * Executing the trade
   * Verifiying the results
      # Checking the trade was valid...PASS

####################
#  Summary:        #
#    Passed = 5    #
#    Failed = 0    #
####################
```

### CODE REVIEW

**Comment by dexX7** [comment]
Shouldn't this be activated *with* the fee stuff?

**Comment by dexX7** [comment]
@zathras-crypto: just a quick heads up and to refine my position: before merging this, I'll locally do more testing with OmniJ.

**Comment by zathras-crypto** [comment]
Awesome thanks dude...

In a nutshell before non-Omni pairs we never had indiv/indiv trading so I thought keeping it separate from fees would allow for easier indiv/indiv testing (since fees will skew the test results).

**Comment by dexX7** [comment]
Well, in the end it's all `int64_t` trading, but we'll see. :)

**Comment by zathras-crypto** [comment]
Also to note is that the UI still applies trading as if each market is only an OMNI/SPT market.

I'll open a new issue as we need to sort out what we're doing with the UI one way or another :)

**Comment by dexX7** [comment]
While testing the trading of indivisible pairs I noticed that the unit price shown in via RPC isn't intuitive:

```js
$ ./src/omnicore-cli omni_gettrade bfa5b67376ef6e0d8ac3d1847a4ff77a19b5e8ec1e4bedd9b645077ec1580eec
{
    "txid" : "bfa5b67376ef6e0d8ac3d1847a4ff77a19b5e8ec1e4bedd9b645077ec1580eec",
    "fee" : "0.00010000",
    "sendingaddress" : "mt4ZF3rNCUVWKBaVGG1ViUJB2PXPb48Gg3",
    "ismine" : true,
    "version" : 0,
    "type_int" : 25,
    "type" : "MetaDEx trade",
    "propertyidforsale" : 3,
    "propertyidforsaleisdivisible" : false,
    "amountforsale" : "50", // <--------------------------------------------------------
    "propertyiddesired" : 4,
    "propertyiddesiredisdivisible" : false,
    "amountdesired" : "20", // <--------------------------------------------------------
    "unitprice" : "0.00000000400000000000000000000000000000000000000000", // <----------
    "amountremaining" : "50",
    "amounttofill" : "20",
    "status" : "open",
    "matches" : [
    ],
    "valid" : true,
    "blockhash" : "5708509c6925a8a4ea0f69c56f542370221c7f4295b9f676746f8ef491250fa6",
    "blocktime" : 1461494061,
    "block" : 113,
    "confirmations" : 1
}
```

20 Indivisble are traded for 50 Indivible, whereby I'd assume the unit price should be `0.4` instead of `0.000000004`, which is the actual unit price, but shown as divisible representation.

**Comment by zathras-crypto** [comment]
> While testing the trading of indivisible pairs I noticed that the unit price shown in via RPC isn't intuitive:

Awesome, thanks for picking that up dude.  I've rewritten ```CMPMetaDEx::displayFullUnitPrice()``` for a direct unit price and did a quick regtest script to check that each of the types (divisible/indivisible) gives an appropriate response here https://github.com/OmniLayer/omnicore/pull/361/commits/fcfe28786004eea600dbea4f84fb77db0d895fc4

> This raises the question: are there other similar assumptions, e.g. in the UI?

The entire UI experience is based on the notion of OMNI being one side of the pair.  We need to do away with the notion of a 'buy' side now otherwise things will start to get confusing (that was doable when all pricing was in OMNI, but I don't think it works for all pair trading).  I'm starting to take a look at the trading UI again at the mo,

**Comment by dexX7** [comment]
I really like your tests! :)

> I've rewritten CMPMetaDEx::displayFullUnitPrice()

Looks good to me! However, it changes the behavior for Omni-pairs. This isn't necessarily a bad thing, and I prefer the consistency, but we should keep it in mind.

> The entire UI experience is based on the notion of OMNI being one side of the pair.

Yes, I'm aware. I was wondering: does non-Omni-pair trading have side effects on the trading interface?

Ideally I'd say we show only xxx/Omni offers in the UI, and filter out xxx/yyy offers without Omni on one side.

**Comment by dexX7** [comment]
Some CI tests fail, because the unit price is inverted.

**Comment by zathras-crypto** [comment]
Not sure what happened to my comment dude, sorry

> Should be updated in the RPC help description, too. :)

Will do.

> Looks good to me! However, it changes the behavior for Omni-pairs. This isn't necessarily a bad thing, and I prefer the consistency, but we should keep it in mind.

Yeah it does, the unit price is always specified in the property desired now.  This makes sense to me, in the context of:
*"It costs N tokens of the desired property to purchase one unit of the property for sale.  Thus N is the unit price."*
Does that make sense to you?

We should also add a note to the release notes highlighting the change in behaviour at the RPC layer.  I don't think we've got any major players (other than OmniWallet) working on integrating MetaDEx at the moment so it shouldn't be too big a problem I hope.

> Yes, I'm aware. I was wondering: does non-Omni-pair trading have side effects on the trading interface?

> Ideally I'd say we show only xxx/Omni offers in the UI, and filter out xxx/yyy offers without Omni on one side.

While iterating the order books the UI assumes that if the trade matches the ```global_metadex_market``` the other side will be Omni.  I started to adapt the old one but it wasn't really working & I've kind of changed quite a lot, but it's given me an opportunity to clean up a bit :)

> Some CI tests fail, because the unit price is inverted.

> edit: I'm going to update them.

Awesome thanks dude :)

**Comment by dexX7** [comment]
@zathras-crypto: I coded a bunch of tests for the activation and trading, and to me all looks good! :)

You may check out [the trading tests](https://github.com/OmniLayer/OmniJ/pull/124/files#diff-f0e319004f929f3fa63c11be692c4cceR229) to double-check. During the tests exact matches are created and the unit price confirmed. For example: 2 SPX trade for 10 SPY -> unit price should be 10.0, inverted price should be 0.2.

**Comment by zathras-crypto** [comment]
> @zathras-crypto: I coded a bunch of tests for the activation and trading, and to me all looks good! :)

That's awesome, thanks so much dude!

**Comment by dexX7** [comment]
What I also noticed: when trading some pairs, for example `9223372036854775807` (indivisible) for `92233720368.54775806` (divisible), then the unit price isn't shown as `x.xxxx..x`, but instead as `x / y`:

```js
{
    ...
    "propertyidforsale" : 5,
    "propertyidforsaleisdivisible" : false,
    "amountforsale" : "9223372036854775807",
    "propertyiddesired" : 6,
    "propertyiddesiredisdivisible" : true,
    "amountdesired" : "92233720368.54775806",
    "unitprice" : "4611686018427387903 / 461168601842738790350000000", // <---
    "amountremaining" : "9223372036854775807",
    "amounttofill" : "92233720368.54775806",
    ...
}

```

This is due to the range of 64 bit numbers and the potentially higher internal representation of `rational_t` (see: [xToString(const rational_t& value)](https://github.com/OmniLayer/omnicore/blob/b9ee7959b5b16c91f6021d26d9b6a62d861dcfac/src/omnicore/mdex.cpp#L114-L124)).

Back then I haven't found a way to deal with it better, but if I recall correctly, I hadn't seen any `x / y` unit prices in the wild until now.

I wouldn't consider this is a major issue, but something to keep in mind, especially for integrators, which may parse unit prices and expect a certain format.

**Comment by dexX7** [comment]
Locally all tests pass.

Once you updated the RPC help descriptions, and you give your final "go", I'd be happy to merge. :)

**Comment by zathras-crypto** [comment]
> then the unit price isn't shown as x.xxxx..x, but instead as x / y

Hmm - that's a really good catch.  Just like you I'm concerned this could break integrations - I'll put this trade on testnet and see how 'Chest copes, but I expect it to fail with the current code base.  Should be simple to fix for 'Chest but I wonder what the best way to handle is.  Perhaps a note in the release notes?  Perhaps extra info in RPC help?

> Locally all tests pass.

Awesome :)

> Once you updated the RPC help descriptions, and you give your final "go", I'd be happy to merge. :)

Doing the RPC help descriptions now.

**Comment by dexX7** [comment]
Alright. :)

Until the testing pull request is merged in OmniJ, Travis CI fails.

**Pull request merged**
